import type { AuditTrailRecord } from "./types";

// --- Mock Data ---
export const MOCK_AUDIT_RECORDS: AuditTrailRecord[] = [
  {
    id: "1",
    timestamp: "03/02/2026, 14:32:18",
    user: "Dr. Sarah Johnson",
    userId: "USR001",
    module: "Document",
    action: "Approve",
    entityId: "SOP.0001.03",
    entityName: "Quality Control Testing SOP",
    description: "Approved document for publication",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "High",
    changes: [
      { field: "status", oldValue: "Pending Approval", newValue: "Approved" },
      { field: "approvedBy", oldValue: "", newValue: "Dr. Sarah Johnson" },
    ],
  },
  {
    id: "2",
    timestamp: "03/02/2026, 13:15:42",
    user: "John Smith",
    userId: "USR005",
    module: "User",
    action: "Create",
    entityId: "USR025",
    entityName: "Jane Doe",
    description: "Created new user account with QA Manager role",
    ipAddress: "192.168.1.12",
    device: "macOS 14.2 - Safari 17.2",
    severity: "Medium",
    changes: [
      { field: "role", oldValue: "", newValue: "QA Manager" },
      { field: "department", oldValue: "", newValue: "Quality Assurance" },
    ],
  },
  {
    id: "3",
    timestamp: "03/02/2026, 12:48:03",
    user: "Michael Chen",
    userId: "USR003",
    module: "CAPA",
    action: "Update",
    entityId: "CAPA-2026-001",
    entityName: "Temperature Excursion Investigation",
    description: "Updated root cause analysis findings",
    ipAddress: "192.168.1.89",
    device: "Windows 11 - Edge 120.0",
    severity: "High",
    changes: [
      { field: "rootCause", oldValue: "Unknown", newValue: "Sensor calibration drift" },
      { field: "status", oldValue: "Investigation", newValue: "Action Plan" },
    ],
  },
  {
    id: "4",
    timestamp: "03/02/2026, 11:22:56",
    user: "Emily Rodriguez",
    userId: "USR008",
    module: "Deviation",
    action: "Create",
    entityId: "DEV-2026-012",
    entityName: "OOS Result - Batch #2024-112",
    description: "Created deviation for out-of-specification test result",
    ipAddress: "192.168.1.67",
    device: "Windows 10 - Chrome 119.0",
    severity: "Critical",
  },
  {
    id: "5",
    timestamp: "03/02/2026, 10:55:31",
    user: "Admin User",
    userId: "USR001",
    module: "System",
    action: "Login",
    entityId: "SESSION-2026-0203-001",
    entityName: "System Login",
    description: "User logged into the system",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "Low",
  },
  {
    id: "6",
    timestamp: "03/02/2026, 10:15:22",
    user: "Dr. Sarah Johnson",
    userId: "USR001",
    module: "Document",
    action: "Download",
    entityId: "SOP.0012.04",
    entityName: "Batch Production Record Procedure",
    description: "Downloaded document PDF",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "Low",
  },
  {
    id: "7",
    timestamp: "03/02/2026, 09:43:17",
    user: "Robert Lee",
    userId: "USR012",
    module: "Training",
    action: "Assign",
    entityId: "TRN-2026-055",
    entityName: "GMP Annual Refresher",
    description: "Assigned training to 15 employees",
    ipAddress: "192.168.1.23",
    device: "macOS 14.2 - Chrome 120.0",
    severity: "Medium",
  },
  {
    id: "8",
    timestamp: "03/02/2026, 09:12:48",
    user: "Michael Chen",
    userId: "USR003",
    module: "CAPA",
    action: "Delete",
    entityId: "CAPA-2026-999",
    entityName: "Duplicate CAPA Entry",
    description: "Deleted duplicate CAPA record",
    ipAddress: "192.168.1.89",
    device: "Windows 11 - Edge 120.0",
    severity: "Medium",
  },
  {
    id: "9",
    timestamp: "02/02/2026, 18:45:33",
    user: "Jane Doe",
    userId: "USR025",
    module: "Document",
    action: "Review",
    entityId: "SOP.0015.02",
    entityName: "Environmental Monitoring Plan",
    description: "Completed technical review",
    ipAddress: "192.168.1.56",
    device: "Windows 10 - Firefox 121.0",
    severity: "Medium",
    changes: [
      { field: "status", oldValue: "Pending Review", newValue: "Review Complete" },
    ],
  },
  {
    id: "10",
    timestamp: "02/02/2026, 16:32:11",
    user: "Admin User",
    userId: "USR001",
    module: "Settings",
    action: "Update",
    entityId: "SYS-CONFIG-001",
    entityName: "System Configuration",
    description: "Updated password policy settings",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "High",
    changes: [
      { field: "minPasswordLength", oldValue: "8", newValue: "12" },
      { field: "passwordExpiry", oldValue: "90", newValue: "60" },
    ],
  },
  {
    id: "11",
    timestamp: "02/02/2026, 15:18:44",
    user: "Emily Rodriguez",
    userId: "USR008",
    module: "Controlled Copy",
    action: "Create",
    entityId: "CC-2026-045",
    entityName: "Controlled Copy Request - Manufacturing Floor",
    description: "Requested controlled copy for production area",
    ipAddress: "192.168.1.67",
    device: "Windows 10 - Chrome 119.0",
    severity: "Low",
  },
  {
    id: "12",
    timestamp: "02/02/2026, 14:05:29",
    user: "David Park",
    userId: "USR015",
    module: "Deviation",
    action: "Approve",
    entityId: "DEV-2026-008",
    entityName: "Equipment Malfunction - Line 3",
    description: "Approved deviation closure",
    ipAddress: "192.168.1.78",
    device: "macOS 13.6 - Safari 17.0",
    severity: "High",
  },
  {
    id: "13",
    timestamp: "02/02/2026, 13:42:55",
    user: "John Smith",
    userId: "USR005",
    module: "User",
    action: "Disable",
    entityId: "USR099",
    entityName: "Former Employee",
    description: "Disabled user account",
    ipAddress: "192.168.1.12",
    device: "Ubuntu 22.04 - Firefox 121.0",
    severity: "Medium",
  },
  {
    id: "14",
    timestamp: "02/02/2026, 12:28:37",
    user: "Dr. Sarah Johnson",
    userId: "USR001",
    module: "Report",
    action: "Export",
    entityId: "RPT-2026-Q1-001",
    entityName: "Quarterly Quality Metrics Report",
    description: "Exported report to Excel",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "Low",
  },
  {
    id: "15",
    timestamp: "02/02/2026, 11:15:22",
    user: "Michael Chen",
    userId: "USR003",
    module: "Document",
    action: "Archive",
    entityId: "SOP.0008.01",
    entityName: "Obsolete Cleaning Procedure",
    description: "Archived obsolete document",
    ipAddress: "192.168.1.89",
    device: "Windows 11 - Edge 120.0",
    severity: "Medium",
  },
  {
    id: "16",
    timestamp: "02/02/2026, 10:47:13",
    user: "Robert Lee",
    userId: "USR012",
    module: "Task",
    action: "Assign",
    entityId: "TSK-2026-089",
    entityName: "Annual Equipment Calibration",
    description: "Assigned task to maintenance team",
    ipAddress: "192.168.1.23",
    device: "macOS 14.2 - Chrome 120.0",
    severity: "Low",
  },
  {
    id: "17",
    timestamp: "01/02/2026, 17:33:48",
    user: "Jane Doe",
    userId: "USR025",
    module: "CAPA",
    action: "Approve",
    entityId: "CAPA-2025-098",
    entityName: "Packaging Material Specification Update",
    description: "Approved CAPA effectiveness verification",
    ipAddress: "192.168.1.56",
    device: "Windows 10 - Firefox 121.0",
    severity: "High",
  },
  {
    id: "18",
    timestamp: "01/02/2026, 16:12:35",
    user: "Emily Rodriguez",
    userId: "USR008",
    module: "Notification",
    action: "Create",
    entityId: "NOT-2026-234",
    entityName: "System Maintenance Notification",
    description: "Created notification for scheduled maintenance",
    ipAddress: "192.168.1.67",
    device: "Windows 10 - Chrome 119.0",
    severity: "Low",
  },
  {
    id: "19",
    timestamp: "01/02/2026, 14:55:29",
    user: "David Park",
    userId: "USR015",
    module: "Document",
    action: "Publish",
    entityId: "POL.0012.01",
    entityName: "Data Integrity Policy",
    description: "Published policy to all users",
    ipAddress: "192.168.1.78",
    device: "macOS 13.6 - Safari 17.0",
    severity: "Critical",
  },
  {
    id: "20",
    timestamp: "01/02/2026, 13:28:17",
    user: "Admin User",
    userId: "USR001",
    module: "System",
    action: "Logout",
    entityId: "SESSION-2026-0201-001",
    entityName: "System Logout",
    description: "User logged out of the system",
    ipAddress: "192.168.1.45",
    device: "Windows 11 - Chrome 120.0",
    severity: "Low",
  },
];
