import type { Task } from "./types";

// --- Mock Data ---
export const MOCK_TASKS: Task[] = [
  {
    id: "1",
    taskId: "SOP-REV-001",
    title: "Review SOP: Batch Release Proc 2.0",
    description:
      "Review the updated sampling plan appendices. Ensure alignment with Annex 16.",
    module: "Document",
    priority: "High",
    dueDate: "25/01/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "System",
    progress: 0,
    timeline: [{ date: "01/01/2026", action: "Task Created", user: "System" }],
  },
  {
    id: "2",
    taskId: "SOP-APR-002",
    title: "Approve Revision: Quality Control Testing SOP v3.0",
    description:
      "Please review and approve the updated quality control testing procedures to comply with new regulatory requirements.",
    module: "Document",
    priority: "Critical",
    dueDate: "15/01/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "John Smith",
    progress: 0,
    timeline: [
      { date: "05/01/2026", action: "Revision Submitted", user: "John Smith" },
      { date: "06/01/2026", action: "Review Completed", user: "QA Team" },
    ],
  },
  {
    id: "3",
    taskId: "DEV-2025-001",
    title: "Investigate Temp Excursion: Warehouse",
    description:
      "Root cause analysis for Zone B sensor failure. Interview logistics staff.",
    module: "Deviation",
    priority: "Critical",
    dueDate: "08/01/2026",
    status: "In-Progress",
    assignee: "Dr. A. Smith",
    reporter: "W. House",
    progress: 45,
    timeline: [
      { date: "20/12/2025", action: "Deviation Logged", user: "W. House" },
      {
        date: "21/12/2025",
        action: "Investigation Started",
        user: "Dr. A. Smith",
      },
    ],
  },
  {
    id: "4",
    taskId: "TRN-2025-055",
    title: "Complete: GMP Annual Refresher Quiz",
    description: "Annual mandatory training requirement.",
    module: "Training",
    priority: "Medium",
    dueDate: "15/01/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "HR Training",
    progress: 0,
    timeline: [{ date: "01/12/2025", action: "Assigned", user: "HR Training" }],
  },
  {
    id: "5",
    taskId: "CAPA-2025-012",
    title: "Verify Effectiveness: Labeling Fix",
    description:
      "Check new label stock for adhesion properties after fix implementation.",
    module: "CAPA",
    priority: "Medium",
    dueDate: "20/01/2026",
    status: "Reviewing",
    assignee: "J. Doe",
    reporter: "QA Lead",
    progress: 90,
    timeline: [
      { date: "01/12/2025", action: "CAPA Opened", user: "QA Lead" },
      { date: "15/12/2025", action: "Actions Implemented", user: "Ops Team" },
      { date: "02/01/2026", action: "Verification Started", user: "J. Doe" },
    ],
  },
  {
    id: "5",
    taskId: "DOC-APR-102",
    title: "Approve: Cleaning Validation Report",
    description: "Final approval required for Line 4.",
    module: "Document",
    priority: "High",
    dueDate: "10/01/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "V. Validation",
    progress: 10,
    timeline: [],
  },
  {
    id: "6",
    taskId: "CC-2025-004",
    title: "Impact Assessment: New HVAC Filter",
    description: "Assess impact on air change rates.",
    module: "Document",
    priority: "Low",
    dueDate: "15/02/2026",
    status: "In-Progress",
    assignee: "Engineering",
    reporter: "Fac. Manager",
    progress: 30,
    timeline: [],
  },
  {
    id: "7",
    taskId: "DEV-2025-003",
    title: "Root Cause Analysis: pH Meter Drift",
    description: "Investigate potential electrode aging.",
    module: "Deviation",
    priority: "Medium",
    dueDate: "30/01/2026",
    status: "Pending",
    assignee: "QC Lab",
    reporter: "QC Lead",
    progress: 0,
    timeline: [],
  },
  {
    id: "8",
    taskId: "TRN-2025-060",
    title: "Read & Understand: Data Integrity Policy",
    description: "New global policy rollout.",
    module: "Training",
    priority: "Low",
    dueDate: "05/02/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "HR Training",
    progress: 0,
    timeline: [],
  },
  {
    id: "9",
    taskId: "CAPA-2025-009",
    title: "Update Risk Assessment for Line 3",
    description: "Post-audit requirement.",
    module: "CAPA",
    priority: "Critical",
    dueDate: "28/12/2025",
    status: "Completed",
    assignee: "QA Risk",
    reporter: "Auditor Ext",
    progress: 100,
    timeline: [],
  },
  {
    id: "10",
    taskId: "SOP-REV-015",
    title: "Review SOP: Pest Control Program",
    description: "Regular biennial review.",
    module: "Document",
    priority: "Low",
    dueDate: "01/03/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "System",
    progress: 0,
    timeline: [],
  },
  {
    id: "11",
    taskId: "DEV-2025-005",
    title: "Material Discrepancy Lot #992",
    description: "Quantity mismatch in raw material receipt.",
    module: "Deviation",
    priority: "High",
    dueDate: "22/01/2026",
    status: "Pending",
    assignee: "Warehousing",
    reporter: "Supply Chain",
    progress: 5,
    timeline: [],
  },
  {
    id: "12",
    taskId: "TRN-2025-061",
    title: "Sterile Gowning Qualification",
    description: "Physical demonstration required.",
    module: "Training",
    priority: "High",
    dueDate: "10/02/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "Microbio QA",
    progress: 0,
    timeline: [],
  },
  {
    id: "13",
    taskId: "DOC-REV-103",
    title: "Review: Environmental Monitoring Plan",
    description: "Update sampling points map.",
    module: "Document",
    priority: "High",
    dueDate: "12/01/2026",
    status: "Pending",
    assignee: "Dr. A. Smith",
    reporter: "EM Lead",
    progress: 0,
    timeline: [],
  },
];
