import type { DocumentType, DocumentStatus } from "@/features/documents/types";

export interface RelatedDocument {
  id: string;
  documentNumber: string;
  documentName: string;
  revisionNumber: string;
  type: DocumentType;
  state: DocumentStatus;
}

export interface CorrelatedDocument {
  id: string;
  documentNumber: string;
  documentName: string;
  revisionNumber: string;
  type: DocumentType;
  state: DocumentStatus;
  correlationType?: string;
}

export interface Document {
  id: string;
  documentId: string;
  title: string;
  type: DocumentType;
  version: string;
  status: DocumentStatus;
  effectiveDate: string;
  validUntil: string;
  author: string;
  businessUnit: string;
  department: string;
  created: string;
  openedBy: string;
  description?: string;
  hasRelatedDocuments?: boolean;
  hasCorrelatedDocuments?: boolean;
  isTemplate?: boolean;
  relatedDocuments?: RelatedDocument[];
  correlatedDocuments?: CorrelatedDocument[];
}

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "1",
    documentId: "SOP.0001.03",
    title: "Standard Operating Procedure for Quality Control Testing",
    type: "SOP",
    version: "3.0",
    status: "Active",
    effectiveDate: "15/06/2023",
    validUntil: "15/06/2024",
    author: "Dr. Sarah Johnson",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "01/05/2023",
    openedBy: "QA Admin",
    description: "Comprehensive procedure for conducting quality control tests on pharmaceutical products",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
    isTemplate: true,
    relatedDocuments: [
      { id: "rel-doc1-1", documentNumber: "SOP.0001.02", documentName: "Quality Control Annexure", revisionNumber: "1.1", type: "SOP", state: "Effective" },
      { id: "rel-doc1-2", documentNumber: "FORM.0001.01", documentName: "QC Inspection Checklist", revisionNumber: "2.0", type: "Form", state: "Effective" },
      { id: "rel-doc1-3", documentNumber: "POL.0002.01", documentName: "Quality Assurance Policy", revisionNumber: "3.0", type: "Policy", state: "Approved" },
    ],
    correlatedDocuments: [
      { id: "cor-doc1-1", documentNumber: "SOP.0005.01", documentName: "Laboratory Safety SOP", revisionNumber: "1.0", type: "SOP", state: "Effective", correlationType: "Reference" },
      { id: "cor-doc1-2", documentNumber: "SPEC.0002.01", documentName: "Raw Material Specification", revisionNumber: "2.0", type: "Specification", state: "Effective", correlationType: "Compliance" },
    ],
  },
  {
    id: "2",
    documentId: "POL.0005.02",
    title: "Quality Management System Policy",
    type: "Policy",
    version: "2.1",
    status: "Draft",
    effectiveDate: "01/08/2023",
    validUntil: "01/08/2024",
    author: "Michael Chen",
    businessUnit: "Quality",
    department: "Quality Management",
    created: "10/07/2023",
    openedBy: "System Admin",
    description: "Organization-wide quality management policy framework",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "3",
    documentId: "SOP.0012.04",
    title: "Batch Production Record Procedure",
    type: "SOP",
    version: "4.2",
    status: "Active",
    effectiveDate: "10/09/2023",
    validUntil: "10/09/2024",
    author: "Emma Williams",
    businessUnit: "Operations",
    department: "Production",
    created: "20/08/2023",
    openedBy: "Production Lead",
    description: "Guidelines for maintaining and reviewing batch production records",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
    isTemplate: true,
    relatedDocuments: [
      { id: "rel-doc3-1", documentNumber: "SOP.0012.03", documentName: "Batch Record Review Procedure", revisionNumber: "3.0", type: "SOP", state: "Effective" },
      { id: "rel-doc3-2", documentNumber: "FORM.0003.01", documentName: "Batch Release Form", revisionNumber: "1.0", type: "Form", state: "Approved" },
    ],
  },
  {
    id: "4",
    documentId: "FORM.0001.01",
    title: "Deviation Report Form",
    type: "Form",
    version: "1.5",
    status: "Obsoleted",
    effectiveDate: "20/05/2022",
    validUntil: "20/05/2023",
    author: "John Davis",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "15/04/2022",
    openedBy: "QA Manager",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
    correlatedDocuments: [
      { id: "cor-doc4-1", documentNumber: "SOP.0001.03", documentName: "QC Testing SOP", revisionNumber: "3.0", type: "SOP", state: "Active", correlationType: "Reference" },
    ],
  },
  {
    id: "5",
    documentId: "SPEC.0045.02",
    title: "Raw Material Specification - API Grade A",
    type: "Specification",
    version: "2.0",
    status: "Active",
    effectiveDate: "01/07/2023",
    validUntil: "01/07/2024",
    author: "Dr. Lisa Park",
    businessUnit: "Quality",
    department: "Quality Control",
    created: "01/06/2023",
    openedBy: "QC Supervisor",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
    relatedDocuments: [
      { id: "rel-doc5-1", documentNumber: "SOP.0001.03", documentName: "QC Testing SOP", revisionNumber: "3.0", type: "SOP", state: "Active" },
      { id: "rel-doc5-2", documentNumber: "FORM.0001.01", documentName: "Deviation Report Form", revisionNumber: "1.5", type: "Form", state: "Obsoleted" },
    ],
    correlatedDocuments: [
      { id: "cor-doc5-1", documentNumber: "POL.0005.02", documentName: "Quality Management System Policy", revisionNumber: "2.1", type: "Policy", state: "Draft", correlationType: "Compliance" },
      { id: "cor-doc5-2", documentNumber: "PROT.0008.03", documentName: "Cleaning Validation Protocol", revisionNumber: "3.1", type: "Protocol", state: "Draft", correlationType: "Reference" },
    ],
  },
  {
    id: "6",
    documentId: "PROT.0008.03",
    title: "Cleaning Validation Protocol",
    type: "Protocol",
    version: "3.1",
    status: "Draft",
    effectiveDate: "15/04/2023",
    validUntil: "15/04/2024",
    author: "Robert Taylor",
    businessUnit: "Research",
    department: "Validation",
    created: "10/03/2023",
    openedBy: "Validation Team",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "7",
    documentId: "REP.0001.01",
    title: "Internal Audit Report Q2 2023",
    type: "Report",
    version: "1.0",
    status: "Closed - Cancelled",
    effectiveDate: "30/06/2023",
    validUntil: "30/06/2024",
    author: "Amanda Martinez",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "20/06/2023",
    openedBy: "Audit Team",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "8",
    documentId: "SOP.0023.05",
    title: "Equipment Calibration Procedure",
    type: "SOP",
    version: "5.0",
    status: "Active",
    effectiveDate: "15/08/2023",
    validUntil: "15/08/2024",
    author: "David Brown",
    businessUnit: "Operations",
    department: "Engineering",
    created: "25/07/2023",
    openedBy: "Engineering Lead",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "9",
    documentId: "SOP.0007.02",
    title: "Training Management Standard Operating Procedure",
    type: "SOP",
    version: "2.3",
    status: "Draft",
    effectiveDate: "01/10/2023",
    validUntil: "01/10/2024",
    author: "Jessica Lee",
    businessUnit: "Corporate",
    department: "Human Resources",
    created: "15/09/2023",
    openedBy: "HR Manager",
    hasCorrelatedDocuments: false,
  },
  {
    id: "10",
    documentId: "POL.0002.01",
    title: "Data Integrity Policy",
    type: "Policy",
    version: "1.0",
    status: "Obsoleted",
    effectiveDate: "01/09/2022",
    validUntil: "01/09/2023",
    author: "Dr. Sarah Johnson",
    businessUnit: "Quality",
    department: "Quality Management",
    created: "10/08/2022",
    openedBy: "QM Director",
    hasCorrelatedDocuments: true,
  },
  {
    id: "11",
    documentId: "SOP.0015.04",
    title: "Good Manufacturing Practice Guidelines",
    type: "SOP",
    version: "4.2",
    status: "Closed - Cancelled",
    effectiveDate: "15/10/2023",
    validUntil: "15/10/2024",
    author: "Michael Chen",
    businessUnit: "Operations",
    department: "Manufacturing",
    created: "01/09/2023",
    openedBy: "Manufacturing Manager",
    description: "Comprehensive GMP guidelines for pharmaceutical manufacturing",
    hasCorrelatedDocuments: false,
  },
  {
    id: "12",
    documentId: "SOP-QA-001",
    title: "Standard Operating Procedure for Quality Control Testing",
    type: "SOP",
    version: "1.0",
    status: "Active",
    effectiveDate: "01/02/2026",
    validUntil: "01/02/2028",
    author: "John Smith",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "05/01/2026",
    openedBy: "Nguyen Van A",
    description: "This SOP outlines the procedures for quality control testing of pharmaceutical products.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "13",
    documentId: "SOP-QA-002",
    title: "Quality Assurance Documentation Standards",
    type: "SOP",
    version: "2.0",
    status: "Draft",
    effectiveDate: "05/02/2026",
    validUntil: "05/02/2028",
    author: "Jane Doe",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "06/01/2026",
    openedBy: "Nguyen Van A",
    description: "Standards for maintaining QA documentation in compliance with regulatory requirements.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "14",
    documentId: "SOP-QA-003",
    title: "Environmental Monitoring Procedures",
    type: "SOP",
    version: "1.5",
    status: "Obsoleted",
    effectiveDate: "10/02/2026",
    validUntil: "10/02/2028",
    author: "Robert Lee",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "07/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for environmental monitoring in controlled manufacturing areas.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: true,
  },
  {
    id: "15",
    documentId: "SOP-QA-004",
    title: "Calibration and Maintenance of Equipment",
    type: "SOP",
    version: "3.0",
    status: "Closed - Cancelled",
    effectiveDate: "15/02/2026",
    validUntil: "15/02/2028",
    author: "Emily Chen",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "08/01/2026",
    openedBy: "Nguyen Van A",
    description: "Guidelines for calibration and preventive maintenance of laboratory equipment.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
  },
  {
    id: "16",
    documentId: "SOP-QA-005",
    title: "Deviation Management Procedures",
    type: "SOP",
    version: "1.0",
    status: "Active",
    effectiveDate: "20/02/2026",
    validUntil: "20/02/2028",
    author: "David Park",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "09/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for identifying, investigating, and resolving deviations from SOPs.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "17",
    documentId: "SOP-QA-006",
    title: "Change Control Procedures",
    type: "SOP",
    version: "2.1",
    status: "Draft",
    effectiveDate: "01/03/2026",
    validUntil: "01/03/2028",
    author: "Sarah Jones",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "15/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for managing changes to documents, equipment, and processes.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: true,
  },
  {
    id: "18",
    documentId: "SOP-QA-007",
    title: "Customer Complaint Handling",
    type: "SOP",
    version: "1.3",
    status: "Active",
    effectiveDate: "05/03/2026",
    validUntil: "05/03/2028",
    author: "Mike Brown",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "20/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for receiving, investigating, and resolving customer complaints.",
    hasRelatedDocuments: false,
    hasCorrelatedDocuments: false,
  },
  {
    id: "19",
    documentId: "SOP-QA-008",
    title: "Vendor Qualification",
    type: "SOP",
    version: "3.2",
    status: "Obsoleted",
    effectiveDate: "10/03/2026",
    validUntil: "10/03/2028",
    author: "Lisa Wilson",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "25/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for qualifying and monitoring vendors of raw materials and services.",
    hasRelatedDocuments: true,
    hasCorrelatedDocuments: false,
  },
  {
    id: "20",
    documentId: "SOP-QA-009",
    title: "Product Recall Procedures",
    type: "SOP",
    version: "1.1",
    status: "Closed - Cancelled",
    effectiveDate: "15/03/2026",
    validUntil: "15/03/2028",
    author: "Tom Clark",
    businessUnit: "Quality",
    department: "Quality Assurance",
    created: "30/01/2026",
    openedBy: "Nguyen Van A",
    description: "Procedures for initiating and managing product recalls.",
    hasRelatedDocuments: false,
  }
];

// Mock current user
export const CURRENT_USER = {
  id: "1",
  name: "Dr. Sarah Johnson",
  role: "Quality Manager",
};

// Mock published templates
export const MOCK_TEMPLATES = [
  { label: "SOP Template v1.0", value: "sop-template-v1" },
  { label: "SOP Template v2.0", value: "sop-template-v2" },
  { label: "Quality Control Template", value: "qc-template-v1" },
  { label: "Work Instruction Template", value: "wi-template-v1" },
];
