import { Complaint } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_COMPLAINTS: Complaint[] = [
  {
    id: "1",
    complaintId: "CMP-2026-001",
    title: "Tablet Discoloration Reported by Distributor",
    description: "Distributor reported yellow discoloration on white-coated tablets in batch TAB-2026-008",
    type: "Product Quality",
    priority: "High",
    status: "Under Investigation",
    source: "Distributor",
    reportedBy: "MedDistrib EU GmbH",
    reportedDate: "22/01/2026",
    affectedProduct: "Amoxicillin 500mg Tablets",
    affectedBatch: "TAB-2026-008",
    country: "Germany",
    responseDeadline: "29/01/2026",
    assignedTo: "Dr. Anna Schmidt",
    createdAt: "22/01/2026, 09:30:00",
    updatedAt: "25/01/2026, 14:00:00",
  },
  {
    id: "2",
    complaintId: "CMP-2026-002",
    title: "Adverse Event - Injection Site Reaction",
    description: "Patient reported severe swelling at injection site after administration",
    type: "Adverse Event",
    priority: "Critical",
    status: "Under Investigation",
    source: "Healthcare Professional",
    reportedBy: "Dr. Jean-Pierre Moreau",
    reportedDate: "24/01/2026",
    affectedProduct: "Ceftriaxone 1g IV Solution",
    affectedBatch: "INJ-2026-003",
    country: "France",
    responseDeadline: "25/01/2026",
    assignedTo: "Pharmacovigilance Team",
    reviewer: "PV Manager",
    createdAt: "24/01/2026, 11:00:00",
    updatedAt: "25/01/2026, 08:30:00",
  },
  {
    id: "3",
    complaintId: "CMP-2026-003",
    title: "Packaging Defect - Missing Patient Leaflet",
    description: "5 units received without patient information leaflet in secondary packaging",
    type: "Packaging",
    priority: "Medium",
    status: "Root Cause Identified",
    source: "Customer",
    reportedBy: "PharmaCare Pharmacy",
    reportedDate: "18/01/2026",
    affectedProduct: "Metformin 850mg Tablets",
    affectedBatch: "TAB-2025-145",
    country: "Spain",
    rootCause: "Leaflet insertion sensor malfunction during packaging run",
    responseDeadline: "25/01/2026",
    assignedTo: "Packaging Engineering",
    createdAt: "18/01/2026, 15:20:00",
    updatedAt: "23/01/2026, 10:45:00",
  },
  {
    id: "4",
    complaintId: "CMP-2025-089",
    title: "Labeling Error - Wrong Strength on Carton",
    description: "Carton label shows 250mg instead of 500mg for correct blister strips",
    type: "Labeling",
    priority: "Critical",
    status: "CAPA Initiated",
    source: "Internal",
    reportedBy: "QA Inspector",
    reportedDate: "15/12/2025",
    affectedProduct: "Ibuprofen Tablets",
    affectedBatch: "TAB-2025-130",
    country: "Italy",
    rootCause: "Artwork version control failure in printing process",
    relatedCapaId: "CAPA-2025-042",
    responseDeadline: "22/12/2025",
    assignedTo: "Artwork Management Team",
    reviewer: "QA Director",
    createdAt: "15/12/2025, 08:00:00",
    updatedAt: "10/01/2026, 09:30:00",
  },
  {
    id: "5",
    complaintId: "CMP-2025-075",
    title: "Temperature Excursion During Delivery",
    description: "Temperature logger showed excursion above 25°C for 6 hours during transit",
    type: "Delivery",
    priority: "Medium",
    status: "Closed",
    source: "Distributor",
    reportedBy: "ColdChain Logistics",
    reportedDate: "28/11/2025",
    affectedProduct: "Insulin Glargine Pens",
    affectedBatch: "BIO-2025-067",
    country: "Netherlands",
    rootCause: "Refrigerated truck breakdown during transit",
    investigationFindings: "Stability data confirms product integrity within excursion range",
    responseDeadline: "05/12/2025",
    assignedTo: "QA Team",
    reviewer: "QA Manager",
    closedDate: "10/12/2025",
    createdAt: "28/11/2025, 14:15:00",
    updatedAt: "10/12/2025, 16:00:00",
  },
];
