import type { SystemInfo, ChangelogEntry } from "./types";

export const MOCK_CHANGELOG: ChangelogEntry[] = [
  {
    version: "2.5.1",
    releaseDate: "01/02/2026",
    changes: {
      features: [
        "Added system health monitoring dashboard",
        "Enhanced API performance metrics tracking",
        "Implemented real-time memory usage graphs",
      ],
      improvements: [
        "Optimized database connection pooling",
        "Improved server uptime calculation accuracy",
        "Enhanced export functionality with custom date ranges",
      ],
      bugFixes: [
        "Fixed incorrect CPU usage percentage display",
        "Resolved memory leak in system monitoring service",
      ],
    },
  },
  {
    version: "2.5.0",
    releaseDate: "15/01/2026",
    changes: {
      features: [
        "Added license management interface",
        "Implemented feature flag configuration UI",
        "Added API endpoint health monitoring",
      ],
      improvements: [
        "Enhanced system information refresh mechanism",
        "Improved database backup status tracking",
      ],
    },
  },
  {
    version: "2.4.8",
    releaseDate: "20/12/2025",
    changes: {
      improvements: [
        "Enhanced error handling for system metrics collection",
        "Improved clipboard copy functionality",
      ],
      bugFixes: [
        "Fixed date formatting issues in system logs",
        "Resolved tab switching animation glitches",
        "Fixed export JSON formatting errors",
      ],
    },
  },
  {
    version: "2.4.5",
    releaseDate: "10/11/2025",
    changes: {
      features: [
        "Added comprehensive system information view",
        "Implemented tabbed navigation for system components",
      ],
      bugFixes: [
        "Fixed server uptime calculation",
      ],
    },
  },
];

export const MOCK_SYSTEM_INFO: SystemInfo = {
  application: {
    name: "eQMS - Quality Management System",
    version: "2.5.1",
    environment: "production",
    buildDate: "01/02/2026, 10:30:00",
    buildNumber: "20260201.1030",
    description: "Enterprise Quality Management System for pharmaceutical and medical device industries",
    frameworkVersion: "React 18.3.1",
    typeScriptVersion: "5.4.5",
    buildTool: "Vite 5.2.0",
  },
  server: {
    os: "Ubuntu 22.04.3 LTS",
    nodeVersion: "v20.11.0",
    memoryTotal: "16 GB",
    memoryUsed: "10.4 GB",
    memoryUsagePercent: 65,
    cpuCores: 8,
    cpuModel: "Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz",
    cpuUsagePercent: 34,
    uptime: "45 days, 12 hours, 34 minutes",
    diskTotal: "500 GB",
    diskUsed: "287 GB",
    diskUsagePercent: 57,
    networkInterfaces: [
      { name: "eth0", ipAddress: "10.0.1.50", type: "IPv4", status: "up" },
      { name: "eth1", ipAddress: "192.168.1.10", type: "IPv4", status: "up" },
      { name: "lo", ipAddress: "127.0.0.1", type: "IPv4", status: "up" },
    ],
    processCount: 142,
    loadAverage: "1.24, 1.08, 0.96",
  },
  database: {
    type: "PostgreSQL",
    version: "15.4",
    host: "db.eqms.internal",
    port: "5432",
    database: "eqms_production",
    connectionStatus: "connected",
    lastBackup: "09/02/2026, 02:00:00",
    connectionPool: {
      maxSize: 50,
      activeConnections: 18,
      idleConnections: 12,
      waitingRequests: 0,
      avgResponseTime: "3.2 ms",
    },
    tableStats: [
      { name: "documents", rowCount: 15420, size: "2.3 GB", lastModified: "26/02/2026, 08:15:00" },
      { name: "users", rowCount: 287, size: "12 MB", lastModified: "26/02/2026, 07:30:00" },
      { name: "audit_logs", rowCount: 892451, size: "4.1 GB", lastModified: "26/02/2026, 09:00:00" },
      { name: "tasks", rowCount: 3247, size: "156 MB", lastModified: "25/02/2026, 16:45:00" },
      { name: "training_records", rowCount: 8124, size: "340 MB", lastModified: "24/02/2026, 14:20:00" },
      { name: "capa_records", rowCount: 542, size: "89 MB", lastModified: "25/02/2026, 11:30:00" },
      { name: "deviations", rowCount: 1203, size: "198 MB", lastModified: "26/02/2026, 06:00:00" },
      { name: "change_controls", rowCount: 387, size: "67 MB", lastModified: "23/02/2026, 09:15:00" },
    ],
    totalSize: "8.7 GB",
    activeConnections: 18,
    maxConnections: 100,
  },
  api: {
    baseUrl: "https://api.eqms.company.com/v2",
    version: "2.5.1",
    status: "online",
    lastHealthCheck: "09/02/2026, 08:45:32",
    responseTime: "42 ms",
    endpoints: [
      { method: "GET", path: "/api/v2/documents", description: "List documents", status: "healthy", avgResponseTime: "38 ms" },
      { method: "POST", path: "/api/v2/documents", description: "Create document", status: "healthy", avgResponseTime: "125 ms" },
      { method: "GET", path: "/api/v2/users", description: "List users", status: "healthy", avgResponseTime: "22 ms" },
      { method: "POST", path: "/api/v2/auth/login", description: "User authentication", status: "healthy", avgResponseTime: "89 ms" },
      { method: "GET", path: "/api/v2/tasks", description: "List tasks", status: "healthy", avgResponseTime: "31 ms" },
      { method: "GET", path: "/api/v2/audit-trail", description: "Query audit logs", status: "degraded", avgResponseTime: "245 ms" },
      { method: "POST", path: "/api/v2/esign", description: "Electronic signature", status: "healthy", avgResponseTime: "156 ms" },
      { method: "GET", path: "/api/v2/reports", description: "Generate reports", status: "healthy", avgResponseTime: "890 ms" },
    ],
    requestStats: {
      totalRequests24h: 45892,
      successRate: 99.87,
      avgResponseTime: "67 ms",
      peakResponseTime: "1.2 s",
      errorCount24h: 59,
      topEndpoints: [
        { path: "/api/v2/documents", count: 12450 },
        { path: "/api/v2/tasks", count: 8930 },
        { path: "/api/v2/auth/login", count: 5240 },
        { path: "/api/v2/audit-trail", count: 4120 },
        { path: "/api/v2/users", count: 3890 },
      ],
    },
    rateLimiting: {
      enabled: true,
      requestsPerMinute: 60,
      burstLimit: 100,
      currentUsage: 23,
    },
  },
  features: [
    {
      id: "esignature",
      name: "Electronic Signature (21 CFR Part 11)",
      description: "Digital signature functionality compliant with FDA regulations",
      enabled: true,
      category: "Document Control",
    },
    {
      id: "batch-review",
      name: "Batch Review & Approval",
      description: "Review and approve multiple documents simultaneously",
      enabled: true,
      category: "Document Control",
    },
    {
      id: "document-linking",
      name: "Document Cross-Referencing",
      description: "Link related documents and track dependencies",
      enabled: true,
      category: "Document Control",
    },
    {
      id: "training-management",
      name: "Training Management",
      description: "Track training requirements and completion status",
      enabled: true,
      category: "Training",
    },
    {
      id: "controlled-copies",
      name: "Controlled Copy Management",
      description: "Manage distribution of physical/electronic controlled copies",
      enabled: true,
      category: "Document Control",
    },
    {
      id: "audit-trail",
      name: "Comprehensive Audit Trail",
      description: "Complete tracking of all system activities and changes",
      enabled: true,
      category: "Compliance",
    },
    {
      id: "change-control",
      name: "Change Control Module",
      description: "Manage change requests and impact assessments",
      enabled: true,
      category: "Quality Management",
    },
    {
      id: "capa",
      name: "CAPA (Corrective & Preventive Actions)",
      description: "Track and manage corrective and preventive actions",
      enabled: true,
      category: "Quality Management",
    },
    {
      id: "deviations",
      name: "Deviation Management",
      description: "Record and investigate deviations from procedures",
      enabled: true,
      category: "Quality Management",
    },
    {
      id: "complaints",
      name: "Customer Complaints",
      description: "Log and track customer complaints",
      enabled: false,
      category: "Quality Management",
    },
    {
      id: "validation",
      name: "Validation Protocols",
      description: "Manage equipment and process validation",
      enabled: false,
      category: "Compliance",
    },
    {
      id: "supplier-management",
      name: "Supplier Quality Management",
      description: "Track supplier qualifications and audits",
      enabled: false,
      category: "Supply Chain",
    },
  ],
  license: {
    licenseType: "Enterprise",
    companyName: "Pharmaceutical Manufacturing Co., Ltd.",
    issuedDate: "01/03/2025",
    expiryDate: "28/02/2027",
    daysUntilExpiry: 384,
    maxUsers: 500,
    activeUsers: 287,
    licenseKey: "EQMS-ENT-2025-XXXX-XXXX-XXXX",
    supportLevel: "Premium 24/7",
    supportEmail: "enterprise-support@eqms.com",
    modules: [
      "Document Control",
      "Training Management",
      "Change Control",
      "CAPA",
      "Deviations",
      "Audit Trail",
      "Controlled Copies",
      "Electronic Signature",
    ],
  },

  storage: {
    provider: "AWS S3",
    totalStorage: "500 GB",
    usedStorage: "187.4 GB",
    usagePercent: 37.5,
    documentsCount: 12847,
    attachmentsCount: 3456,
    backupsCount: 14,
    fileTypeBreakdown: [
      { type: "PDF", count: 6234, size: "78.2 GB", percentage: 41.7 },
      { type: "DOCX", count: 3156, size: "45.6 GB", percentage: 24.3 },
      { type: "XLSX", count: 1842, size: "28.9 GB", percentage: 15.4 },
      { type: "Images", count: 987, size: "18.4 GB", percentage: 9.8 },
      { type: "Other", count: 628, size: "16.3 GB", percentage: 8.7 },
    ],
    recentUploads: [
      {
        fileName: "SOP-QC-2025-001.pdf",
        uploadedBy: "Dr. Sarah Johnson",
        uploadedAt: "14/07/2025, 10:23:00",
        size: "4.2 MB",
        type: "PDF",
      },
      {
        fileName: "Training-Record-Batch-45.xlsx",
        uploadedBy: "Michael Chen",
        uploadedAt: "14/07/2025, 09:15:00",
        size: "1.8 MB",
        type: "XLSX",
      },
      {
        fileName: "Deviation-Report-DEV-2025-089.pdf",
        uploadedBy: "Emily Watson",
        uploadedAt: "13/07/2025, 16:45:00",
        size: "3.1 MB",
        type: "PDF",
      },
      {
        fileName: "CAPA-Evidence-IMG-001.png",
        uploadedBy: "James Rodriguez",
        uploadedAt: "13/07/2025, 14:30:00",
        size: "5.7 MB",
        type: "Images",
      },
      {
        fileName: "Change-Control-CC-2025-012.docx",
        uploadedBy: "Lisa Park",
        uploadedAt: "13/07/2025, 11:20:00",
        size: "2.4 MB",
        type: "DOCX",
      },
    ],
  },
};
