import {
  FileText,
  Calendar,
  GitBranch,
  Users,
  Clock,
  TrendingUp,
  AlertTriangle,
  BarChart3,
  CheckCircle2,
  ShieldAlert,
  MessageSquareWarning,
  History,
  ClipboardCheck,
  BookOpen,
  Truck,
  Activity,
  Target,
  Gauge,
  PieChart,
  LineChart,
  Layers,
  ListChecks,
  FileSearch,
  Scale,
  Wrench,
  ThermometerSun,
  Timer,
  Building2,
} from 'lucide-react';
import type { ReportTemplate, ReportHistory, ScheduledReport } from './types';
import { IconRefresh } from '@tabler/icons-react';

// --- Report Templates ---
export const REPORT_TEMPLATES: ReportTemplate[] = [
  // ═══════════════════════════════════════════
  // Document Reports
  // ═══════════════════════════════════════════
  {
    id: 'doc-status',
    name: 'Document Status Report',
    type: 'Document',
    description: 'Overview of all documents by status, type, and department. Tracks document lifecycle.',
    icon: FileText,
    fields: [
      { id: 'doc-number', label: 'Document Number', group: 'General', defaultEnabled: true },
      { id: 'doc-title', label: 'Document Title', group: 'General', defaultEnabled: true },
      { id: 'doc-type', label: 'Document Type', group: 'General', defaultEnabled: true },
      { id: 'doc-status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'doc-version', label: 'Version', group: 'General', defaultEnabled: true },
      { id: 'doc-department', label: 'Department', group: 'Organization', defaultEnabled: true },
      { id: 'doc-owner', label: 'Document Owner', group: 'Organization', defaultEnabled: true },
      { id: 'doc-effective-date', label: 'Effective Date', group: 'Dates', defaultEnabled: true },
      { id: 'doc-review-date', label: 'Next Review Date', group: 'Dates', defaultEnabled: false },
      { id: 'doc-created-date', label: 'Created Date', group: 'Dates', defaultEnabled: false },
      { id: 'doc-approval-history', label: 'Approval History', group: 'Details', defaultEnabled: false },
      { id: 'doc-change-summary', label: 'Change Summary', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'doc-expiry',
    name: 'Document Expiry Report',
    type: 'Document',
    description: 'Documents approaching expiration or review date. Critical for compliance.',
    icon: Calendar,
    regulatoryRef: 'EU-GMP Chapter 4',
    fields: [
      { id: 'doc-number', label: 'Document Number', group: 'General', defaultEnabled: true },
      { id: 'doc-title', label: 'Document Title', group: 'General', defaultEnabled: true },
      { id: 'doc-expiry-date', label: 'Expiry Date', group: 'General', defaultEnabled: true },
      { id: 'doc-days-remaining', label: 'Days Remaining', group: 'General', defaultEnabled: true },
      { id: 'doc-owner', label: 'Document Owner', group: 'Organization', defaultEnabled: true },
      { id: 'doc-department', label: 'Department', group: 'Organization', defaultEnabled: true },
      { id: 'doc-urgency', label: 'Urgency Level', group: 'Details', defaultEnabled: false },
      { id: 'doc-last-review', label: 'Last Review Date', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'doc-version-control',
    name: 'Document Version Control Report',
    type: 'Document',
    description: 'Tracks all document revisions, changes, and version history.',
    icon: GitBranch,
    fields: [
      { id: 'doc-number', label: 'Document Number', group: 'General', defaultEnabled: true },
      { id: 'doc-title', label: 'Document Title', group: 'General', defaultEnabled: true },
      { id: 'doc-current-version', label: 'Current Version', group: 'General', defaultEnabled: true },
      { id: 'doc-previous-versions', label: 'Previous Versions', group: 'History', defaultEnabled: true },
      { id: 'doc-change-reason', label: 'Change Reason', group: 'History', defaultEnabled: true },
      { id: 'doc-changed-by', label: 'Changed By', group: 'History', defaultEnabled: false },
      { id: 'doc-change-date', label: 'Change Date', group: 'History', defaultEnabled: false },
    ],
  },
  {
    id: 'doc-distribution',
    name: 'Document Distribution Report',
    type: 'Document',
    description: 'Tracks controlled copy distribution, recipient acknowledgment, and obsolete returns.',
    icon: Layers,
    fields: [
      { id: 'doc-number', label: 'Document Number', group: 'General', defaultEnabled: true },
      { id: 'copy-number', label: 'Copy Number', group: 'General', defaultEnabled: true },
      { id: 'recipient', label: 'Recipient', group: 'Distribution', defaultEnabled: true },
      { id: 'location', label: 'Location', group: 'Distribution', defaultEnabled: true },
      { id: 'dist-date', label: 'Distribution Date', group: 'Distribution', defaultEnabled: true },
      { id: 'acknowledged', label: 'Acknowledged', group: 'Status', defaultEnabled: true },
      { id: 'return-status', label: 'Return Status', group: 'Status', defaultEnabled: false },
    ],
  },
  {
    id: 'doc-obsolete',
    name: 'Obsolete Documents Report',
    type: 'Document',
    description: 'Lists all obsoleted and archived documents with destruction records.',
    icon: FileSearch,
    fields: [
      { id: 'doc-number', label: 'Document Number', group: 'General', defaultEnabled: true },
      { id: 'doc-title', label: 'Document Title', group: 'General', defaultEnabled: true },
      { id: 'obsolete-date', label: 'Obsolete Date', group: 'General', defaultEnabled: true },
      { id: 'superseded-by', label: 'Superseded By', group: 'Details', defaultEnabled: true },
      { id: 'destruction-record', label: 'Destruction Record', group: 'Details', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Training Reports
  // ═══════════════════════════════════════════
  {
    id: 'training-completion',
    name: 'Training Completion Report',
    type: 'Training',
    description: 'Training completion status by user and course. Shows compliance percentage.',
    icon: Users,
    regulatoryRef: 'EU-GMP Chapter 2',
    fields: [
      { id: 'employee-name', label: 'Employee Name', group: 'Employee', defaultEnabled: true },
      { id: 'employee-id', label: 'Employee Code', group: 'Employee', defaultEnabled: true },
      { id: 'department', label: 'Department', group: 'Employee', defaultEnabled: true },
      { id: 'job-title', label: 'Job Title', group: 'Employee', defaultEnabled: false },
      { id: 'course-name', label: 'Course Name', group: 'Training', defaultEnabled: true },
      { id: 'completion-status', label: 'Completion Status', group: 'Training', defaultEnabled: true },
      { id: 'completion-date', label: 'Completion Date', group: 'Training', defaultEnabled: true },
      { id: 'score', label: 'Assessment Score', group: 'Training', defaultEnabled: false },
      { id: 'compliance-pct', label: 'Compliance %', group: 'Metrics', defaultEnabled: true },
    ],
  },
  {
    id: 'training-overdue',
    name: 'Training Overdue Report',
    type: 'Training',
    description: 'List of overdue training assignments by user and department.',
    icon: Clock,
    fields: [
      { id: 'employee-name', label: 'Employee Name', group: 'Employee', defaultEnabled: true },
      { id: 'department', label: 'Department', group: 'Employee', defaultEnabled: true },
      { id: 'course-name', label: 'Course Name', group: 'Training', defaultEnabled: true },
      { id: 'due-date', label: 'Due Date', group: 'Training', defaultEnabled: true },
      { id: 'days-overdue', label: 'Days Overdue', group: 'Training', defaultEnabled: true },
      { id: 'manager', label: 'Manager', group: 'Employee', defaultEnabled: false },
      { id: 'escalation-level', label: 'Escalation Level', group: 'Status', defaultEnabled: false },
    ],
  },
  {
    id: 'training-effectiveness',
    name: 'Training Effectiveness Report',
    type: 'Training',
    description: 'Measures training effectiveness through assessments and performance metrics.',
    icon: TrendingUp,
    fields: [
      { id: 'course-name', label: 'Course Name', group: 'Training', defaultEnabled: true },
      { id: 'avg-score', label: 'Average Score', group: 'Metrics', defaultEnabled: true },
      { id: 'pass-rate', label: 'Pass Rate', group: 'Metrics', defaultEnabled: true },
      { id: 'total-enrolled', label: 'Total Enrolled', group: 'Metrics', defaultEnabled: true },
      { id: 'pre-post-comparison', label: 'Pre/Post Comparison', group: 'Analysis', defaultEnabled: false },
      { id: 'feedback-summary', label: 'Feedback Summary', group: 'Analysis', defaultEnabled: false },
    ],
  },
  {
    id: 'training-matrix',
    name: 'Training Matrix Report',
    type: 'Training',
    description: 'Cross-reference matrix of employees vs. required training with completion status.',
    icon: ListChecks,
    fields: [
      { id: 'employee-name', label: 'Employee Name', group: 'Employee', defaultEnabled: true },
      { id: 'department', label: 'Department', group: 'Employee', defaultEnabled: true },
      { id: 'role', label: 'Role', group: 'Employee', defaultEnabled: true },
      { id: 'required-trainings', label: 'Required Trainings', group: 'Matrix', defaultEnabled: true },
      { id: 'completion-status', label: 'Status per Training', group: 'Matrix', defaultEnabled: true },
      { id: 'overall-compliance', label: 'Overall Compliance', group: 'Metrics', defaultEnabled: true },
    ],
  },
  {
    id: 'training-certification',
    name: 'Certification Tracking Report',
    type: 'Training',
    description: 'Tracks professional certifications, expiry dates, and renewal requirements.',
    icon: ClipboardCheck,
    fields: [
      { id: 'employee-name', label: 'Employee Name', group: 'Employee', defaultEnabled: true },
      { id: 'certification', label: 'Certification', group: 'Certification', defaultEnabled: true },
      { id: 'issue-date', label: 'Issue Date', group: 'Certification', defaultEnabled: true },
      { id: 'expiry-date', label: 'Expiry Date', group: 'Certification', defaultEnabled: true },
      { id: 'renewal-status', label: 'Renewal Status', group: 'Status', defaultEnabled: true },
    ],
  },

  // ═══════════════════════════════════════════
  // Deviation Reports
  // ═══════════════════════════════════════════
  {
    id: 'deviation-summary',
    name: 'Deviation Summary Report',
    type: 'Deviation',
    description: 'Summary of deviations by severity, status, and root cause. Includes trending.',
    icon: AlertTriangle,
    regulatoryRef: 'EU-GMP Chapter 8',
    fields: [
      { id: 'dev-number', label: 'Deviation Number', group: 'General', defaultEnabled: true },
      { id: 'dev-title', label: 'Title', group: 'General', defaultEnabled: true },
      { id: 'dev-severity', label: 'Severity', group: 'General', defaultEnabled: true },
      { id: 'dev-status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'dev-department', label: 'Department', group: 'General', defaultEnabled: true },
      { id: 'dev-root-cause', label: 'Root Cause Category', group: 'Analysis', defaultEnabled: true },
      { id: 'dev-opened-date', label: 'Opened Date', group: 'Dates', defaultEnabled: true },
      { id: 'dev-closed-date', label: 'Closed Date', group: 'Dates', defaultEnabled: false },
      { id: 'dev-impact', label: 'Impact Assessment', group: 'Analysis', defaultEnabled: false },
      { id: 'dev-linked-capa', label: 'Linked CAPA', group: 'Analysis', defaultEnabled: false },
    ],
  },
  {
    id: 'deviation-rca',
    name: 'Root Cause Analysis Report',
    type: 'Deviation',
    description: 'Detailed root cause analysis for deviations with CAPA linkage.',
    icon: BarChart3,
    fields: [
      { id: 'dev-number', label: 'Deviation Number', group: 'General', defaultEnabled: true },
      { id: 'rca-method', label: 'RCA Method', group: 'Analysis', defaultEnabled: true },
      { id: 'root-cause', label: 'Root Cause', group: 'Analysis', defaultEnabled: true },
      { id: 'contributing-factors', label: 'Contributing Factors', group: 'Analysis', defaultEnabled: true },
      { id: 'capa-number', label: 'CAPA Number', group: 'Linkage', defaultEnabled: true },
      { id: 'effectiveness', label: 'CAPA Effectiveness', group: 'Linkage', defaultEnabled: false },
    ],
  },
  {
    id: 'deviation-closure',
    name: 'Deviation Closure Time Report',
    type: 'Deviation',
    description: 'Tracks time to close deviations. Identifies bottlenecks in investigation.',
    icon: Clock,
    fields: [
      { id: 'dev-number', label: 'Deviation Number', group: 'General', defaultEnabled: true },
      { id: 'opened-date', label: 'Opened Date', group: 'Dates', defaultEnabled: true },
      { id: 'closed-date', label: 'Closed Date', group: 'Dates', defaultEnabled: true },
      { id: 'days-open', label: 'Days Open', group: 'Metrics', defaultEnabled: true },
      { id: 'target-days', label: 'Target Days', group: 'Metrics', defaultEnabled: true },
      { id: 'on-time', label: 'On Time?', group: 'Metrics', defaultEnabled: true },
      { id: 'bottleneck-stage', label: 'Bottleneck Stage', group: 'Analysis', defaultEnabled: false },
    ],
  },
  {
    id: 'deviation-trending',
    name: 'Deviation Trending Report',
    type: 'Deviation',
    description: 'Identifies recurring deviations patterns and trends over selectable periods.',
    icon: LineChart,
    fields: [
      { id: 'period', label: 'Period', group: 'General', defaultEnabled: true },
      { id: 'total-count', label: 'Total Count', group: 'Metrics', defaultEnabled: true },
      { id: 'by-severity', label: 'By Severity', group: 'Breakdown', defaultEnabled: true },
      { id: 'by-department', label: 'By Department', group: 'Breakdown', defaultEnabled: true },
      { id: 'by-root-cause', label: 'By Root Cause', group: 'Breakdown', defaultEnabled: false },
      { id: 'trend-chart', label: 'Trend Chart', group: 'Visualization', defaultEnabled: true },
    ],
  },

  // ═══════════════════════════════════════════
  // CAPA Reports
  // ═══════════════════════════════════════════
  {
    id: 'capa-effectiveness',
    name: 'CAPA Effectiveness Report',
    type: 'CAPA',
    description: 'CAPA implementation and effectiveness tracking. Verifies corrective actions work.',
    icon: CheckCircle2,
    regulatoryRef: 'FDA 21 CFR 820.100',
    fields: [
      { id: 'capa-number', label: 'CAPA Number', group: 'General', defaultEnabled: true },
      { id: 'capa-title', label: 'Title', group: 'General', defaultEnabled: true },
      { id: 'source-deviation', label: 'Source Deviation', group: 'General', defaultEnabled: true },
      { id: 'corrective-action', label: 'Corrective Action', group: 'Actions', defaultEnabled: true },
      { id: 'preventive-action', label: 'Preventive Action', group: 'Actions', defaultEnabled: true },
      { id: 'verification-result', label: 'Verification Result', group: 'Effectiveness', defaultEnabled: true },
      { id: 'effectiveness-score', label: 'Effectiveness Score', group: 'Effectiveness', defaultEnabled: true },
      { id: 'recurrence-check', label: 'Recurrence Check', group: 'Effectiveness', defaultEnabled: false },
    ],
  },
  {
    id: 'capa-aging',
    name: 'CAPA Aging Report',
    type: 'CAPA',
    description: 'Lists CAPAs that are overdue or approaching deadline.',
    icon: Clock,
    fields: [
      { id: 'capa-number', label: 'CAPA Number', group: 'General', defaultEnabled: true },
      { id: 'capa-title', label: 'Title', group: 'General', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'due-date', label: 'Due Date', group: 'Dates', defaultEnabled: true },
      { id: 'days-overdue', label: 'Days Overdue', group: 'Metrics', defaultEnabled: true },
      { id: 'owner', label: 'Owner', group: 'Organization', defaultEnabled: true },
      { id: 'priority', label: 'Priority', group: 'General', defaultEnabled: false },
    ],
  },
  {
    id: 'capa-trending',
    name: 'CAPA Trending Report',
    type: 'CAPA',
    description: 'Identifies recurring issues and CAPA patterns over time.',
    icon: TrendingUp,
    fields: [
      { id: 'period', label: 'Period', group: 'General', defaultEnabled: true },
      { id: 'new-capas', label: 'New CAPAs', group: 'Metrics', defaultEnabled: true },
      { id: 'closed-capas', label: 'Closed CAPAs', group: 'Metrics', defaultEnabled: true },
      { id: 'open-capas', label: 'Open CAPAs', group: 'Metrics', defaultEnabled: true },
      { id: 'by-category', label: 'By Category', group: 'Breakdown', defaultEnabled: true },
      { id: 'avg-closure-time', label: 'Avg Closure Time', group: 'Metrics', defaultEnabled: false },
    ],
  },
  {
    id: 'capa-kpi',
    name: 'CAPA KPI Dashboard Report',
    type: 'CAPA',
    description: 'Key performance indicators for CAPA process: on-time rate, effectiveness, recurrence.',
    icon: Gauge,
    fields: [
      { id: 'total-open', label: 'Total Open', group: 'KPI', defaultEnabled: true },
      { id: 'on-time-rate', label: 'On-Time Closure Rate', group: 'KPI', defaultEnabled: true },
      { id: 'effectiveness-rate', label: 'Effectiveness Rate', group: 'KPI', defaultEnabled: true },
      { id: 'recurrence-rate', label: 'Recurrence Rate', group: 'KPI', defaultEnabled: true },
      { id: 'avg-days-to-close', label: 'Avg Days to Close', group: 'KPI', defaultEnabled: true },
      { id: 'by-department', label: 'By Department', group: 'Breakdown', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Change Control Reports
  // ═══════════════════════════════════════════
  {
    id: 'change-summary',
    name: 'Change Control Summary',
    type: 'Change Control',
    description: 'Overview of all changes by type, status, and impact assessment.',
    icon: IconRefresh,
    fields: [
      { id: 'change-number', label: 'Change Number', group: 'General', defaultEnabled: true },
      { id: 'change-title', label: 'Title', group: 'General', defaultEnabled: true },
      { id: 'change-type', label: 'Change Type', group: 'General', defaultEnabled: true },
      { id: 'change-status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'impact-level', label: 'Impact Level', group: 'Assessment', defaultEnabled: true },
      { id: 'requested-by', label: 'Requested By', group: 'Organization', defaultEnabled: true },
      { id: 'request-date', label: 'Request Date', group: 'Dates', defaultEnabled: true },
      { id: 'implementation-date', label: 'Implementation Date', group: 'Dates', defaultEnabled: false },
    ],
  },
  {
    id: 'change-impact',
    name: 'Change Impact Assessment Report',
    type: 'Change Control',
    description: 'Detailed impact assessment for approved changes on systems and processes.',
    icon: ShieldAlert,
    fields: [
      { id: 'change-number', label: 'Change Number', group: 'General', defaultEnabled: true },
      { id: 'affected-systems', label: 'Affected Systems', group: 'Impact', defaultEnabled: true },
      { id: 'affected-docs', label: 'Affected Documents', group: 'Impact', defaultEnabled: true },
      { id: 'risk-assessment', label: 'Risk Assessment', group: 'Impact', defaultEnabled: true },
      { id: 'required-trainings', label: 'Required Trainings', group: 'Impact', defaultEnabled: false },
      { id: 'validation-needed', label: 'Validation Needed', group: 'Impact', defaultEnabled: false },
    ],
  },
  {
    id: 'change-implementation',
    name: 'Change Implementation Status Report',
    type: 'Change Control',
    description: 'Tracks progress of approved change implementations and task completion.',
    icon: Target,
    fields: [
      { id: 'change-number', label: 'Change Number', group: 'General', defaultEnabled: true },
      { id: 'change-title', label: 'Title', group: 'General', defaultEnabled: true },
      { id: 'tasks-completed', label: 'Tasks Completed', group: 'Progress', defaultEnabled: true },
      { id: 'tasks-remaining', label: 'Tasks Remaining', group: 'Progress', defaultEnabled: true },
      { id: 'progress-pct', label: 'Progress %', group: 'Progress', defaultEnabled: true },
      { id: 'target-date', label: 'Target Date', group: 'Dates', defaultEnabled: true },
      { id: 'responsible', label: 'Responsible', group: 'Organization', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Complaint Reports
  // ═══════════════════════════════════════════
  {
    id: 'complaint-trend',
    name: 'Complaint Trend Analysis',
    type: 'Complaint',
    description: 'Analyzes complaint trends by product, category, and severity.',
    icon: MessageSquareWarning,
    regulatoryRef: 'EU-GMP Chapter 8',
    fields: [
      { id: 'period', label: 'Period', group: 'General', defaultEnabled: true },
      { id: 'total-complaints', label: 'Total Complaints', group: 'Metrics', defaultEnabled: true },
      { id: 'by-product', label: 'By Product', group: 'Breakdown', defaultEnabled: true },
      { id: 'by-category', label: 'By Category', group: 'Breakdown', defaultEnabled: true },
      { id: 'by-severity', label: 'By Severity', group: 'Breakdown', defaultEnabled: true },
      { id: 'resolution-time', label: 'Avg Resolution Time', group: 'Metrics', defaultEnabled: false },
      { id: 'trend-chart', label: 'Trend Chart', group: 'Visualization', defaultEnabled: false },
    ],
  },
  {
    id: 'complaint-detail',
    name: 'Complaint Detail Report',
    type: 'Complaint',
    description: 'Detailed complaint records with investigation findings and corrective actions.',
    icon: FileSearch,
    fields: [
      { id: 'complaint-number', label: 'Complaint Number', group: 'General', defaultEnabled: true },
      { id: 'product', label: 'Product', group: 'General', defaultEnabled: true },
      { id: 'category', label: 'Category', group: 'General', defaultEnabled: true },
      { id: 'severity', label: 'Severity', group: 'General', defaultEnabled: true },
      { id: 'investigation-findings', label: 'Investigation Findings', group: 'Details', defaultEnabled: true },
      { id: 'corrective-action', label: 'Corrective Action', group: 'Details', defaultEnabled: true },
      { id: 'reporter-info', label: 'Reporter Info', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'complaint-response-time',
    name: 'Complaint Response Time Report',
    type: 'Complaint',
    description: 'Measures response and resolution times for complaints against SLA targets.',
    icon: Timer,
    fields: [
      { id: 'complaint-number', label: 'Complaint Number', group: 'General', defaultEnabled: true },
      { id: 'received-date', label: 'Received Date', group: 'Dates', defaultEnabled: true },
      { id: 'response-date', label: 'Response Date', group: 'Dates', defaultEnabled: true },
      { id: 'resolution-date', label: 'Resolution Date', group: 'Dates', defaultEnabled: true },
      { id: 'response-days', label: 'Response Days', group: 'Metrics', defaultEnabled: true },
      { id: 'sla-met', label: 'SLA Met?', group: 'Metrics', defaultEnabled: true },
    ],
  },

  // ═══════════════════════════════════════════
  // Audit Reports
  // ═══════════════════════════════════════════
  {
    id: 'audit-trail',
    name: 'Audit Trail Report',
    type: 'Audit',
    description: 'Complete audit trail of system activities by user, module, and time range.',
    icon: History,
    regulatoryRef: 'FDA 21 CFR Part 11',
    fields: [
      { id: 'timestamp', label: 'Timestamp', group: 'General', defaultEnabled: true },
      { id: 'user', label: 'User', group: 'General', defaultEnabled: true },
      { id: 'action', label: 'Action', group: 'General', defaultEnabled: true },
      { id: 'module', label: 'Module', group: 'General', defaultEnabled: true },
      { id: 'record-affected', label: 'Record Affected', group: 'Details', defaultEnabled: true },
      { id: 'old-value', label: 'Old Value', group: 'Details', defaultEnabled: false },
      { id: 'new-value', label: 'New Value', group: 'Details', defaultEnabled: false },
      { id: 'ip-address', label: 'IP Address', group: 'System', defaultEnabled: false },
    ],
  },
  {
    id: 'user-activity',
    name: 'User Activity Report',
    type: 'Audit',
    description: 'Tracks user login/logout, actions performed, and access patterns.',
    icon: Users,
    fields: [
      { id: 'user', label: 'User', group: 'General', defaultEnabled: true },
      { id: 'login-time', label: 'Login Time', group: 'Activity', defaultEnabled: true },
      { id: 'logout-time', label: 'Logout Time', group: 'Activity', defaultEnabled: true },
      { id: 'session-duration', label: 'Session Duration', group: 'Activity', defaultEnabled: true },
      { id: 'actions-count', label: 'Actions Count', group: 'Metrics', defaultEnabled: true },
      { id: 'modules-accessed', label: 'Modules Accessed', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'audit-findings',
    name: 'Audit Findings Report',
    type: 'Audit',
    description: 'Internal and external audit findings, observations, and corrective actions.',
    icon: ClipboardCheck,
    fields: [
      { id: 'audit-id', label: 'Audit ID', group: 'General', defaultEnabled: true },
      { id: 'audit-type', label: 'Audit Type', group: 'General', defaultEnabled: true },
      { id: 'finding', label: 'Finding', group: 'Details', defaultEnabled: true },
      { id: 'severity', label: 'Severity', group: 'Details', defaultEnabled: true },
      { id: 'corrective-action', label: 'Corrective Action', group: 'Response', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'Response', defaultEnabled: true },
      { id: 'due-date', label: 'Due Date', group: 'Response', defaultEnabled: false },
    ],
  },
  {
    id: 'audit-schedule',
    name: 'Audit Schedule Report',
    type: 'Audit',
    description: 'Annual audit schedule with planned vs. completed audits tracker.',
    icon: Calendar,
    fields: [
      { id: 'audit-name', label: 'Audit Name', group: 'General', defaultEnabled: true },
      { id: 'planned-date', label: 'Planned Date', group: 'Dates', defaultEnabled: true },
      { id: 'actual-date', label: 'Actual Date', group: 'Dates', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'auditor', label: 'Auditor', group: 'Organization', defaultEnabled: true },
      { id: 'scope', label: 'Scope', group: 'Details', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Supplier Reports
  // ═══════════════════════════════════════════
  {
    id: 'supplier-performance',
    name: 'Supplier Performance Report',
    type: 'Supplier',
    description: 'Evaluates supplier performance based on quality, delivery, and compliance metrics.',
    icon: Truck,
    fields: [
      { id: 'supplier-name', label: 'Supplier Name', group: 'General', defaultEnabled: true },
      { id: 'supplier-code', label: 'Supplier Code', group: 'General', defaultEnabled: true },
      { id: 'quality-score', label: 'Quality Score', group: 'Metrics', defaultEnabled: true },
      { id: 'delivery-score', label: 'Delivery Score', group: 'Metrics', defaultEnabled: true },
      { id: 'compliance-score', label: 'Compliance Score', group: 'Metrics', defaultEnabled: true },
      { id: 'overall-rating', label: 'Overall Rating', group: 'Metrics', defaultEnabled: true },
      { id: 'ncr-count', label: 'NCR Count', group: 'Quality', defaultEnabled: false },
      { id: 'audit-status', label: 'Audit Status', group: 'Quality', defaultEnabled: false },
    ],
  },
  {
    id: 'supplier-qualification',
    name: 'Supplier Qualification Status Report',
    type: 'Supplier',
    description: 'Tracks supplier qualification, re-qualification, and approval status.',
    icon: Scale,
    fields: [
      { id: 'supplier-name', label: 'Supplier Name', group: 'General', defaultEnabled: true },
      { id: 'qualification-status', label: 'Qualification Status', group: 'Status', defaultEnabled: true },
      { id: 'qualification-date', label: 'Qualification Date', group: 'Dates', defaultEnabled: true },
      { id: 'next-requalification', label: 'Next Requalification', group: 'Dates', defaultEnabled: true },
      { id: 'materials-supplied', label: 'Materials Supplied', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'supplier-ncr',
    name: 'Supplier Non-Conformance Report',
    type: 'Supplier',
    description: 'Non-conformance records related to supplier materials and services.',
    icon: AlertTriangle,
    fields: [
      { id: 'ncr-number', label: 'NCR Number', group: 'General', defaultEnabled: true },
      { id: 'supplier-name', label: 'Supplier Name', group: 'General', defaultEnabled: true },
      { id: 'material', label: 'Material', group: 'General', defaultEnabled: true },
      { id: 'issue-type', label: 'Issue Type', group: 'Details', defaultEnabled: true },
      { id: 'severity', label: 'Severity', group: 'Details', defaultEnabled: true },
      { id: 'corrective-action', label: 'Corrective Action', group: 'Response', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Risk Management Reports
  // ═══════════════════════════════════════════
  {
    id: 'risk-assessment',
    name: 'Risk Assessment Report',
    type: 'Risk Management',
    description: 'Comprehensive risk assessment with likelihood, severity, and RPN calculations.',
    icon: Activity,
    regulatoryRef: 'ICH Q9',
    fields: [
      { id: 'risk-id', label: 'Risk ID', group: 'General', defaultEnabled: true },
      { id: 'risk-title', label: 'Risk Title', group: 'General', defaultEnabled: true },
      { id: 'category', label: 'Category', group: 'General', defaultEnabled: true },
      { id: 'likelihood', label: 'Likelihood', group: 'Assessment', defaultEnabled: true },
      { id: 'severity', label: 'Severity', group: 'Assessment', defaultEnabled: true },
      { id: 'rpn', label: 'RPN Score', group: 'Assessment', defaultEnabled: true },
      { id: 'mitigation', label: 'Mitigation Plan', group: 'Response', defaultEnabled: true },
      { id: 'residual-risk', label: 'Residual Risk', group: 'Response', defaultEnabled: false },
      { id: 'owner', label: 'Risk Owner', group: 'Organization', defaultEnabled: false },
    ],
  },
  {
    id: 'risk-register',
    name: 'Risk Register Report',
    type: 'Risk Management',
    description: 'Complete risk register with all identified risks and their current status.',
    icon: BookOpen,
    fields: [
      { id: 'risk-id', label: 'Risk ID', group: 'General', defaultEnabled: true },
      { id: 'risk-title', label: 'Risk Title', group: 'General', defaultEnabled: true },
      { id: 'risk-level', label: 'Risk Level', group: 'Assessment', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'controls', label: 'Controls', group: 'Response', defaultEnabled: true },
      { id: 'review-date', label: 'Review Date', group: 'Dates', defaultEnabled: true },
    ],
  },
  {
    id: 'risk-heatmap',
    name: 'Risk Heatmap Report',
    type: 'Risk Management',
    description: 'Visual risk heatmap showing risk distribution across likelihood and severity.',
    icon: PieChart,
    fields: [
      { id: 'heatmap-visualization', label: 'Heatmap Visualization', group: 'Visualization', defaultEnabled: true },
      { id: 'high-risk-list', label: 'High Risk List', group: 'Details', defaultEnabled: true },
      { id: 'risk-distribution', label: 'Risk Distribution', group: 'Statistics', defaultEnabled: true },
      { id: 'trend-comparison', label: 'Period Comparison', group: 'Statistics', defaultEnabled: false },
    ],
  },

  // ═══════════════════════════════════════════
  // Equipment Reports
  // ═══════════════════════════════════════════
  {
    id: 'equipment-status',
    name: 'Equipment Status Report',
    type: 'Equipment',
    description: 'Current status of all equipment including calibration and maintenance status.',
    icon: Wrench,
    fields: [
      { id: 'equipment-id', label: 'Equipment ID', group: 'General', defaultEnabled: true },
      { id: 'equipment-name', label: 'Name', group: 'General', defaultEnabled: true },
      { id: 'location', label: 'Location', group: 'General', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'calibration-due', label: 'Calibration Due', group: 'Maintenance', defaultEnabled: true },
      { id: 'maintenance-due', label: 'Maintenance Due', group: 'Maintenance', defaultEnabled: true },
      { id: 'last-calibration', label: 'Last Calibration', group: 'Maintenance', defaultEnabled: false },
    ],
  },
  {
    id: 'equipment-calibration',
    name: 'Calibration Schedule Report',
    type: 'Equipment',
    description: 'Calibration schedule, overdue calibrations, and calibration history.',
    icon: ThermometerSun,
    fields: [
      { id: 'equipment-id', label: 'Equipment ID', group: 'General', defaultEnabled: true },
      { id: 'equipment-name', label: 'Name', group: 'General', defaultEnabled: true },
      { id: 'calibration-date', label: 'Calibration Date', group: 'Dates', defaultEnabled: true },
      { id: 'next-due', label: 'Next Due', group: 'Dates', defaultEnabled: true },
      { id: 'result', label: 'Result', group: 'Details', defaultEnabled: true },
      { id: 'performed-by', label: 'Performed By', group: 'Details', defaultEnabled: false },
      { id: 'certificate-number', label: 'Certificate Number', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'equipment-utilization',
    name: 'Equipment Utilization Report',
    type: 'Equipment',
    description: 'Equipment usage rates, downtime analysis, and efficiency metrics.',
    icon: Gauge,
    fields: [
      { id: 'equipment-id', label: 'Equipment ID', group: 'General', defaultEnabled: true },
      { id: 'equipment-name', label: 'Name', group: 'General', defaultEnabled: true },
      { id: 'utilization-rate', label: 'Utilization Rate', group: 'Metrics', defaultEnabled: true },
      { id: 'uptime', label: 'Uptime', group: 'Metrics', defaultEnabled: true },
      { id: 'downtime', label: 'Downtime', group: 'Metrics', defaultEnabled: true },
      { id: 'downtime-reasons', label: 'Downtime Reasons', group: 'Analysis', defaultEnabled: false },
    ],
  },
];

// --- Compliance Report Templates ---
export const COMPLIANCE_TEMPLATES: ReportTemplate[] = [
  {
    id: 'comp-annex11',
    name: 'EU-GMP Annex 11 Compliance Report',
    type: 'Compliance',
    description: 'Comprehensive compliance report for computerized systems per EU-GMP Annex 11.',
    icon: ShieldAlert,
    regulatoryRef: 'EU-GMP Annex 11',
    fields: [
      { id: 'system-name', label: 'System Name', group: 'General', defaultEnabled: true },
      { id: 'validation-status', label: 'Validation Status', group: 'Compliance', defaultEnabled: true },
      { id: 'access-controls', label: 'Access Controls', group: 'Compliance', defaultEnabled: true },
      { id: 'audit-trail-status', label: 'Audit Trail Status', group: 'Compliance', defaultEnabled: true },
      { id: 'data-integrity', label: 'Data Integrity Controls', group: 'Compliance', defaultEnabled: true },
      { id: 'backup-recovery', label: 'Backup & Recovery', group: 'Compliance', defaultEnabled: false },
      { id: 'periodic-review', label: 'Periodic Review Date', group: 'Monitoring', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-21cfr11',
    name: 'FDA 21 CFR Part 11 Compliance Report',
    type: 'Compliance',
    description: 'Electronic records and electronic signatures compliance report.',
    icon: ClipboardCheck,
    regulatoryRef: 'FDA 21 CFR Part 11',
    fields: [
      { id: 'e-record-controls', label: 'E-Record Controls', group: 'Compliance', defaultEnabled: true },
      { id: 'e-signature-controls', label: 'E-Signature Controls', group: 'Compliance', defaultEnabled: true },
      { id: 'audit-trail', label: 'Audit Trail Compliance', group: 'Compliance', defaultEnabled: true },
      { id: 'system-validation', label: 'System Validation', group: 'Compliance', defaultEnabled: true },
      { id: 'user-authentication', label: 'User Authentication', group: 'Security', defaultEnabled: true },
      { id: 'access-control', label: 'Access Control', group: 'Security', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-data-integrity',
    name: 'Data Integrity Report (ALCOA+)',
    type: 'Compliance',
    description:
      'Evaluates data integrity controls: Attributable, Legible, Contemporaneous, Original, Accurate.',
    icon: ClipboardCheck,
    regulatoryRef: 'MHRA GXP Guidance',
    fields: [
      { id: 'attributable', label: 'Attributable', group: 'ALCOA+', defaultEnabled: true },
      { id: 'legible', label: 'Legible', group: 'ALCOA+', defaultEnabled: true },
      { id: 'contemporaneous', label: 'Contemporaneous', group: 'ALCOA+', defaultEnabled: true },
      { id: 'original', label: 'Original', group: 'ALCOA+', defaultEnabled: true },
      { id: 'accurate', label: 'Accurate', group: 'ALCOA+', defaultEnabled: true },
      { id: 'complete', label: 'Complete', group: 'ALCOA+', defaultEnabled: false },
      { id: 'consistent', label: 'Consistent', group: 'ALCOA+', defaultEnabled: false },
      { id: 'enduring', label: 'Enduring', group: 'ALCOA+', defaultEnabled: false },
      { id: 'available', label: 'Available', group: 'ALCOA+', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-batch-release',
    name: 'Batch Release Report',
    type: 'Compliance',
    description: 'Quality review of batch records for product release authorization.',
    icon: FileText,
    regulatoryRef: 'EU-GMP Chapter 6',
    fields: [
      { id: 'batch-number', label: 'Batch Number', group: 'General', defaultEnabled: true },
      { id: 'product-name', label: 'Product Name', group: 'General', defaultEnabled: true },
      { id: 'release-status', label: 'Release Status', group: 'General', defaultEnabled: true },
      { id: 'qp-review', label: 'QP Review', group: 'Review', defaultEnabled: true },
      { id: 'deviations', label: 'Deviations', group: 'Review', defaultEnabled: true },
      { id: 'oos-results', label: 'OOS Results', group: 'Review', defaultEnabled: false },
      { id: 'stability-data', label: 'Stability Data', group: 'Review', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-quality-review',
    name: 'Quality Review Report',
    type: 'Compliance',
    description: 'Periodic quality review of documented procedures and compliance.',
    icon: BookOpen,
    regulatoryRef: 'EU-GMP Chapter 1',
    fields: [
      { id: 'review-period', label: 'Review Period', group: 'General', defaultEnabled: true },
      { id: 'procedures-reviewed', label: 'Procedures Reviewed', group: 'Scope', defaultEnabled: true },
      { id: 'findings', label: 'Findings', group: 'Results', defaultEnabled: true },
      { id: 'recommendations', label: 'Recommendations', group: 'Results', defaultEnabled: true },
      { id: 'compliance-score', label: 'Compliance Score', group: 'Metrics', defaultEnabled: true },
      { id: 'action-items', label: 'Action Items', group: 'Results', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-apqr',
    name: 'Annual Product Quality Review (APQR)',
    type: 'Compliance',
    description:
      'Annual review of product quality including trends, deviations, changes, and CAPAs.',
    icon: BarChart3,
    regulatoryRef: 'EU-GMP Chapter 1 (1.10)',
    fields: [
      { id: 'product-name', label: 'Product Name', group: 'General', defaultEnabled: true },
      { id: 'batches-produced', label: 'Batches Produced', group: 'Production', defaultEnabled: true },
      { id: 'deviation-summary', label: 'Deviation Summary', group: 'Quality', defaultEnabled: true },
      { id: 'capa-summary', label: 'CAPA Summary', group: 'Quality', defaultEnabled: true },
      { id: 'change-summary', label: 'Change Summary', group: 'Quality', defaultEnabled: true },
      { id: 'complaint-summary', label: 'Complaint Summary', group: 'Quality', defaultEnabled: false },
      { id: 'stability-summary', label: 'Stability Summary', group: 'Quality', defaultEnabled: false },
      { id: 'trend-analysis', label: 'Trend Analysis', group: 'Analysis', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-validation-status',
    name: 'Validation Status Report',
    type: 'Compliance',
    description: 'Status of all validation activities including equipment, process, and cleaning validation.',
    icon: CheckCircle2,
    regulatoryRef: 'EU-GMP Annex 15',
    fields: [
      { id: 'validation-id', label: 'Validation ID', group: 'General', defaultEnabled: true },
      { id: 'type', label: 'Type', group: 'General', defaultEnabled: true },
      { id: 'status', label: 'Status', group: 'General', defaultEnabled: true },
      { id: 'last-validation', label: 'Last Validation', group: 'Dates', defaultEnabled: true },
      { id: 'next-due', label: 'Next Due', group: 'Dates', defaultEnabled: true },
      { id: 'protocol-number', label: 'Protocol Number', group: 'Details', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-management-review',
    name: 'Management Review Report',
    type: 'Compliance',
    description: 'Summary report for management review meetings covering all quality metrics.',
    icon: Building2,
    regulatoryRef: 'ISO 9001:2015 §9.3',
    fields: [
      { id: 'period', label: 'Period', group: 'General', defaultEnabled: true },
      { id: 'quality-objectives', label: 'Quality Objectives', group: 'Performance', defaultEnabled: true },
      { id: 'kpi-summary', label: 'KPI Summary', group: 'Performance', defaultEnabled: true },
      { id: 'deviation-overview', label: 'Deviation Overview', group: 'Modules', defaultEnabled: true },
      { id: 'capa-overview', label: 'CAPA Overview', group: 'Modules', defaultEnabled: true },
      { id: 'training-overview', label: 'Training Overview', group: 'Modules', defaultEnabled: false },
      { id: 'complaint-overview', label: 'Complaint Overview', group: 'Modules', defaultEnabled: false },
      { id: 'resource-needs', label: 'Resource Needs', group: 'Management', defaultEnabled: false },
    ],
  },
  {
    id: 'comp-environmental',
    name: 'Environmental Monitoring Report',
    type: 'Compliance',
    description: 'Environmental monitoring data for cleanrooms and controlled areas.',
    icon: ThermometerSun,
    regulatoryRef: 'EU-GMP Annex 1',
    fields: [
      { id: 'location', label: 'Location', group: 'General', defaultEnabled: true },
      { id: 'classification', label: 'Classification', group: 'General', defaultEnabled: true },
      { id: 'particle-count', label: 'Particle Count', group: 'Monitoring', defaultEnabled: true },
      { id: 'viable-count', label: 'Viable Count', group: 'Monitoring', defaultEnabled: true },
      { id: 'temp-humidity', label: 'Temp/Humidity', group: 'Monitoring', defaultEnabled: true },
      { id: 'alert-excursions', label: 'Alert/Excursions', group: 'Status', defaultEnabled: true },
      { id: 'trend-data', label: 'Trend Data', group: 'Analysis', defaultEnabled: false },
    ],
  },
];

// --- Mock Report History ---
export const MOCK_REPORT_HISTORY: ReportHistory[] = [
  {
    id: '1',
    reportName: 'Document Status Report - Q4 2025',
    type: 'Document',
    format: 'PDF',
    generatedDate: '2026-01-28 14:35',
    generatedBy: 'John Smith',
    period: 'Q4 2025 (Oct-Dec)',
    status: 'Completed',
    fileSize: '2.4 MB',
  },
  {
    id: '2',
    reportName: 'Training Completion Report - December 2025',
    type: 'Training',
    format: 'Excel',
    generatedDate: '2026-01-15 09:20',
    generatedBy: 'Sarah Johnson',
    period: 'December 2025',
    status: 'Completed',
    fileSize: '856 KB',
  },
  {
    id: '3',
    reportName: 'CAPA Effectiveness Report - 2025',
    type: 'CAPA',
    format: 'PDF',
    generatedDate: '2026-01-10 16:45',
    generatedBy: 'Michael Chen',
    period: 'Full Year 2025',
    status: 'Completed',
    fileSize: '3.1 MB',
  },
  {
    id: '4',
    reportName: 'Deviation Summary Report - Q4 2025',
    type: 'Deviation',
    format: 'PDF',
    generatedDate: '2026-01-05 11:10',
    generatedBy: 'Emma Wilson',
    period: 'Q4 2025 (Oct-Dec)',
    status: 'Completed',
    fileSize: '1.8 MB',
  },
  {
    id: '5',
    reportName: 'Audit Trail Report - January 2026',
    type: 'Audit',
    format: 'CSV',
    generatedDate: '2026-01-30 08:00',
    generatedBy: 'System Admin',
    period: 'January 1-30, 2026',
    status: 'In Progress',
    fileSize: '-',
  },
  {
    id: '6',
    reportName: 'EU-GMP Annex 11 Compliance Report',
    type: 'Compliance',
    format: 'PDF',
    generatedDate: '2026-01-02 10:00',
    generatedBy: 'QA Director',
    period: 'Full Year 2025',
    status: 'Completed',
    fileSize: '4.2 MB',
  },
  {
    id: '7',
    reportName: 'Change Control Summary - 2025',
    type: 'Change Control',
    format: 'Excel',
    generatedDate: '2025-12-28 15:30',
    generatedBy: 'Change Coordinator',
    period: 'Full Year 2025',
    status: 'Completed',
    fileSize: '1.2 MB',
  },
];

// --- Mock Scheduled Reports ---
export const MOCK_SCHEDULED_REPORTS: ScheduledReport[] = [
  {
    id: '1',
    reportName: 'Document Expiry Report',
    type: 'Document',
    schedule: 'Weekly - Monday 9:00 AM',
    nextRun: '2026-02-03 09:00',
    recipients: ['qa-team@company.com', 'quality-manager@company.com'],
    status: 'Active',
    lastRun: '2026-01-27 09:00',
  },
  {
    id: '2',
    reportName: 'Training Overdue Report',
    type: 'Training',
    schedule: 'Daily - 8:00 AM',
    nextRun: '2026-02-01 08:00',
    recipients: ['training-dept@company.com', 'hr@company.com'],
    status: 'Active',
    lastRun: '2026-01-31 08:00',
  },
  {
    id: '3',
    reportName: 'CAPA Aging Report',
    type: 'CAPA',
    schedule: 'Bi-weekly - Friday 10:00 AM',
    nextRun: '2026-02-07 10:00',
    recipients: ['capa-team@company.com'],
    status: 'Active',
    lastRun: '2026-01-24 10:00',
  },
  {
    id: '4',
    reportName: 'Monthly Quality Metrics',
    type: 'Compliance',
    schedule: 'Monthly - 1st day 7:00 AM',
    nextRun: '2026-03-01 07:00',
    recipients: ['senior-management@company.com', 'quality-dept@company.com'],
    status: 'Active',
    lastRun: '2026-01-01 07:00',
  },
  {
    id: '5',
    reportName: 'Deviation Summary Report',
    type: 'Deviation',
    schedule: 'Quarterly - 1st Monday 9:00 AM',
    nextRun: '2026-04-07 09:00',
    recipients: ['quality-manager@company.com'],
    status: 'Paused',
    lastRun: '2025-10-07 09:00',
  },
];
