import type { Role } from "./types";
import { PERMISSION_GROUPS } from "./constants";

// TODO: Replace with API call: GET /api/settings/roles
export const MOCK_ROLES: Role[] = [
  {
    id: "1",
    name: "System Administrator",
    description: "Full system access with all permissions. Responsible for system configuration and user management.",
    type: "system",
    isActive: true,
    userCount: 2,
    color: "bg-red-50 text-red-700 border-red-200",
    createdDate: "2024-01-15",
    modifiedDate: "2024-01-15",
    permissions: PERMISSION_GROUPS.flatMap(g => g.permissions.map(p => p.id)),
  },
  {
    id: "2",
    name: "QA Manager",
    description: "Quality Assurance oversight. Can approve documents, review CAPAs, and access audit trails.",
    type: "system",
    isActive: true,
    userCount: 5,
    color: "bg-purple-50 text-purple-700 border-purple-200",
    createdDate: "2024-01-15",
    modifiedDate: "2024-06-20",
    permissions: [
      "doc_view", "doc_review", "doc_approve", "doc_archive", "doc_print",
      "train_view", "train_manage_view", "train_assign",
      "train_course_create", "train_course_edit", "train_course_review", "train_course_approve",
      "train_result_entry",
      "train_mat_view", "train_mat_upload", "train_mat_edit", "train_mat_review", "train_mat_obsolete",
      "train_matrix_view", "train_compliance_view", "train_records_export",
      "capa_view", "capa_approve", "capa_close",
      "cc_view", "cc_review", "cc_approve", "cc_close",
      "dev_view", "dev_approve",
      "risk_view", "risk_approve",
      "supp_view", "supp_audit", "supp_approve",
      "audit_view", "audit_export",
      "user_view", "user_create", "user_edit",
      "settings_view",
    ],
  },
  {
    id: "3",
    name: "Department Head",
    description: "Department-level document management and team supervision. Can create and edit documents within department scope.",
    type: "system",
    isActive: true,
    userCount: 8,
    color: "bg-blue-50 text-blue-700 border-blue-200",
    createdDate: "2024-01-15",
    modifiedDate: "2024-03-10",
    permissions: [
      "doc_view", "doc_create", "doc_edit", "doc_review", "doc_print",
      "train_view", "train_manage_view", "train_assign",
      "train_course_create", "train_course_edit", "train_course_review",
      "train_result_entry",
      "train_mat_view", "train_mat_upload", "train_mat_edit",
      "train_matrix_view", "train_compliance_view", "train_records_export",
      "capa_view", "capa_create", "capa_edit", "capa_review",
      "cc_view", "cc_create", "cc_edit",
      "dev_view", "dev_create", "dev_edit",
      "risk_view", "risk_create", "risk_edit",
      "supp_view",
      "user_view",
    ],
  },
  {
    id: "4",
    name: "Document Owner",
    description: "Document creation and maintenance. Primary author for controlled documents.",
    type: "custom",
    isActive: true,
    userCount: 15,
    color: "bg-cyan-50 text-cyan-700 border-cyan-200",
    createdDate: "2024-02-01",
    modifiedDate: "2024-08-15",
    permissions: [
      "doc_view", "doc_create", "doc_edit",
      "train_view", "train_mat_view", "train_mat_upload", "train_mat_edit",
      "train_course_create", "train_result_entry", "train_compliance_view",
      "capa_view", "capa_create",
      "cc_view", "cc_create",
      "dev_view", "dev_create",
    ],
  },
  {
    id: "5",
    name: "Reviewer",
    description: "Document review workflow participant. Can review documents but not approve.",
    type: "custom",
    isActive: true,
    userCount: 12,
    color: "bg-emerald-50 text-emerald-700 border-emerald-200",
    createdDate: "2024-02-01",
    modifiedDate: "2024-05-22",
    permissions: [
      "doc_view", "doc_review",
      "train_view", "train_mat_view", "train_mat_review", "train_course_review",
      "capa_view",
      "cc_view", "cc_review",
      "dev_view",
    ],
  },
  {
    id: "6",
    name: "Standard User",
    description: "Basic read-only access. Can view approved documents and assigned training.",
    type: "custom",
    isActive: true,
    userCount: 45,
    color: "bg-slate-50 text-slate-700 border-slate-200",
    createdDate: "2024-01-15",
    modifiedDate: "2024-01-15",
    permissions: [
      "doc_view",
      "train_view", "train_mat_view",
      "capa_view",
      "cc_view",
      "dev_view",
    ],
  },
  {
    id: "7",
    name: "Auditor",
    description: "Internal/external auditor access. Read-only with audit trail export capability.",
    type: "system",
    isActive: true,
    userCount: 3,
    color: "bg-amber-50 text-amber-700 border-amber-200",
    createdDate: "2024-03-01",
    modifiedDate: "2024-03-01",
    permissions: [
      "doc_view",
      "train_view", "train_mat_view", "train_matrix_view", "train_compliance_view", "train_records_export",
      "capa_view",
      "cc_view",
      "dev_view",
      "audit_view", "audit_export",
    ],
  },
];
