import type { User } from "./types";

// TODO: Replace with API call: GET /api/settings/users
export const MOCK_USERS: User[] = [
  {
    id: "1",
    employeeCode: "NTP.0001",
    fullName: "Admin Hệ Thống 1",
    username: "adminhethong",
    email: "admin@zenithquality.com",
    phone: "0911263575",
    role: "Admin",
    businessUnit: "Corporate",
    department: "IT Department",
    status: "Active",
    lastLogin: "2025-12-31 14:30",
    createdDate: "2024-01-15",
    jobTitle: "System Administrator",
    dateOfBirth: "1985-03-20",
    gender: "Male",
    nationality: "Vietnamese",
    address: "123 Nguyễn Huệ, Quận 1, TP.HCM",
    employmentType: "Full-time",
    startDate: "2024-01-15",
    managerName: "N/A",
    permissions: [],
    educationList: [
      {
        id: "edu-1",
        degree: "Bachelor of Science",
        fieldOfStudy: "Software Engineering",
        institution: "Ho Chi Minh City University of Technology",
        graduationYear: "2007",
        gpa: "3.6/4.0",
      }
    ],
  },
  {
    id: "2",
    employeeCode: "NTP.0002",
    fullName: "Dr. Amanda Smith",
    username: "a.smith",
    email: "a.smith@zenithquality.com",
    phone: "+1-555-0123",
    role: "QA Manager",
    businessUnit: "Quality",
    department: "Quality Assurance",
    status: "Active",
    lastLogin: "2025-12-31 13:15",
    createdDate: "2024-02-20",
    jobTitle: "QA Manager",
    dateOfBirth: "1980-07-12",
    gender: "Female",
    nationality: "American",
    address: "456 Oak Street, Boston, MA 02110",
    employmentType: "Full-time",
    startDate: "2024-02-20",
    managerName: "Admin Hệ Thống 1",
    permissions: [],
    educationList: [
      {
        id: "edu-2",
        degree: "Doctor of Philosophy (PhD)",
        fieldOfStudy: "Quality Management",
        institution: "Harvard University",
        graduationYear: "2015",
        gpa: "3.9/4.0",
      },
      {
        id: "edu-3",
        degree: "Master of Science",
        fieldOfStudy: "Industrial Engineering",
        institution: "Stanford University",
        graduationYear: "2010",
        gpa: "3.8/4.0",
      }
    ],
  },
  {
    id: "3",
    employeeCode: "NTP.0003",
    fullName: "John Doe",
    username: "j.doe",
    email: "j.doe@zenithquality.com",
    phone: "+1-555-0124",
    role: "Document Owner",
    businessUnit: "Quality",
    department: "Quality Assurance",
    status: "Active",
    lastLogin: "2025-12-30 16:45",
    createdDate: "2024-03-10",
    jobTitle: "Quality Specialist",
    dateOfBirth: "1990-11-05",
    gender: "Male",
    nationality: "American",
    address: "789 Elm Ave, New York, NY 10001",
    employmentType: "Full-time",
    startDate: "2024-03-10",
    managerName: "Dr. Amanda Smith",
    permissions: [],
    educationList: [
      {
        id: "edu-4",
        degree: "Bachelor of Science",
        fieldOfStudy: "Biology",
        institution: "University of California, Berkeley",
        graduationYear: "2012",
        gpa: "3.5/4.0",
      }
    ],
  },
  {
    id: "4",
    employeeCode: "NTP.0004",
    fullName: "Jane Wilson",
    username: "j.wilson",
    email: "j.wilson@zenithquality.com",
    phone: "+1-555-0125",
    role: "Reviewer",
    businessUnit: "Quality",
    department: "Regulatory Affairs",
    status: "Active",
    lastLogin: "2025-12-31 10:20",
    createdDate: "2024-04-05",
    jobTitle: "Regulatory Affairs Specialist",
    dateOfBirth: "1992-02-28",
    gender: "Female",
    nationality: "British",
    address: "321 Maple Drive, Chicago, IL 60601",
    employmentType: "Full-time",
    startDate: "2024-04-05",
    managerName: "Dr. Amanda Smith",
    permissions: [],
  },
  {
    id: "5",
    employeeCode: "NTP.0005",
    fullName: "Michael Brown",
    username: "m.brown",
    email: "m.brown@zenithquality.com",
    phone: "+1-555-0126",
    role: "Approver",
    businessUnit: "Quality",
    department: "Quality Assurance",
    status: "Inactive",
    lastLogin: "2025-12-20 09:30",
    createdDate: "2024-05-12",
    jobTitle: "Senior QA Engineer",
    dateOfBirth: "1978-09-15",
    gender: "Male",
    nationality: "Canadian",
    address: "654 Pine Road, Seattle, WA 98101",
    employmentType: "Contract",
    startDate: "2024-05-12",
    managerName: "Dr. Amanda Smith",
    permissions: [],
  },
  {
    id: "6",
    employeeCode: "NTP.0006",
    fullName: "Sarah Johnson",
    username: "s.johnson",
    email: "s.johnson@zenithquality.com",
    phone: "+1-555-0127",
    role: "Viewer",
    businessUnit: "Operations",
    department: "Production",
    status: "Active",
    lastLogin: "2025-12-31 12:00",
    createdDate: "2024-06-18",
    jobTitle: "Production Coordinator",
    dateOfBirth: "1995-06-22",
    gender: "Female",
    nationality: "American",
    address: "987 Cedar Lane, Austin, TX 73301",
    employmentType: "Full-time",
    startDate: "2024-06-18",
    managerName: "Admin Hệ Thống 1",
    permissions: [],
  },
  {
    id: "7",
    employeeCode: "NTP.0007",
    fullName: "Robert Taylor",
    username: "r.taylor",
    email: "r.taylor@zenithquality.com",
    phone: "+1-555-0128",
    role: "Document Owner",
    businessUnit: "Research",
    department: "R&D",
    status: "Pending",
    lastLogin: "Never",
    createdDate: "2025-12-30",
    jobTitle: "Research Scientist",
    dateOfBirth: "1988-04-10",
    gender: "Male",
    nationality: "Australian",
    address: "159 Willow Blvd, San Francisco, CA 94102",
    employmentType: "Full-time",
    startDate: "2025-12-30",
    managerName: "Admin Hệ Thống 1",
    permissions: [],
  },
  {
    id: "8",
    employeeCode: "NTP.0008",
    fullName: "Emily Chen",
    username: "e.chen",
    email: "e.chen@zenithquality.com",
    phone: "+1-555-0129",
    role: "Reviewer",
    businessUnit: "Quality",
    department: "Quality Control",
    status: "Suspended",
    lastLogin: "2026-01-10 08:45",
    createdDate: "2024-08-01",
    jobTitle: "QC Analyst",
    dateOfBirth: "1993-05-17",
    gender: "Female",
    nationality: "Chinese",
    address: "22 Harbor View, San Diego, CA 92101",
    employmentType: "Full-time",
    startDate: "2024-08-01",
    managerName: "Dr. Amanda Smith",
    suspendReason: "Pending internal investigation",
    suspendedUntil: "2026-04-30",
    permissions: [],
  },
  {
    id: "9",
    employeeCode: "NTP.0009",
    fullName: "David Martinez",
    username: "d.martinez",
    email: "d.martinez@zenithquality.com",
    phone: "+1-555-0130",
    role: "Viewer",
    businessUnit: "Operations",
    department: "Logistics",
    status: "Terminated",
    lastLogin: "2025-11-28 17:00",
    createdDate: "2023-06-15",
    jobTitle: "Logistics Coordinator",
    dateOfBirth: "1987-08-03",
    gender: "Male",
    nationality: "Mexican",
    address: "88 Sunset Blvd, Los Angeles, CA 90001",
    employmentType: "Full-time",
    startDate: "2023-06-15",
    managerName: "Admin Hệ Thống 1",
    terminationReason: "Resignation",
    terminationDate: "2025-12-01",
    permissions: [],
  },
];

// TODO: Replace with API call: GET /api/settings/users/:id
export const MOCK_USER: User = {
  ...MOCK_USERS[0]
};

// TODO: Replace with API call: GET /api/settings/users (for duplicate detection)
export const EXISTING_USERS: { employeeCode: string; email: string }[] = [
  { employeeCode: "0001", email: "admin@zenithquality.com" },
  { employeeCode: "0002", email: "a.smith@zenithquality.com" },
];
