import type { TrainingRecord, TrainingFile, TrainingStatus, CourseApproval, EnrollmentStatus, ResultStatus, EmployeeProgress, CourseProgressInfo } from "../../types";

// Mock training files
export const MOCK_TRAINING_FILES: TrainingFile[] = [
  {
    id: "tf-001",
    file: null as any,
    name: "GMP_Training_Materials_2026.pdf",
    size: 2456789,
    type: "application/pdf",
    progress: 100,
    status: "success",
  },
  {
    id: "tf-002",
    file: null as any,
    name: "GMP_Presentation_Slides.pptx",
    size: 8765432,
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    progress: 100,
    status: "success",
  },
  {
    id: "tf-003",
    file: null as any,
    name: "Quick_Reference_Guide.docx",
    size: 567890,
    type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    progress: 100,
    status: "success",
  },
];

// Mock courses — in real app, fetch from API by ID
export const MOCK_COURSES: (TrainingRecord & {
  trainingFiles: TrainingFile[];
  instruction: string;
  examTemplate?: string;
  answerKey?: string;
  passingGradeType?: "pass_fail" | "score_10" | "percentage";
  maxAttempts?: number;
  questions: any[];
  instructorType: "internal" | "external";
  linkedDocumentId: string;
  linkedDocumentTitle: string;
})[] = [
  {
    id: "1",
    trainingId: "TRN-2026-001",
    title: "GMP Basic Principles",
    description:
      "This comprehensive training covers the fundamental principles of Good Manufacturing Practice (GMP) required for all personnel working in pharmaceutical manufacturing environments.",
    type: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Effective",
    instructor: "Dr. Sarah Williams",
    instructorType: "internal",
    scheduledDate: "15/03/2026",
    duration: 4,
    location: "Training Room A",
    capacity: 25,
    enrolled: 20,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 80,
    version: "v1.0",
    recurrence: { enabled: true, intervalMonths: 12, warningPeriodDays: 30 },
    linkedDocumentId: "DOC-001",
    linkedDocumentTitle: "SOP-QA-001: Good Manufacturing Practices",
    trainingFiles: MOCK_TRAINING_FILES,
    instruction:
      "Focus on Chapter 3 (Cleaning Validation) and Appendix B (Equipment Handling). Review all SOPs referenced in Section 2.4 before the training session.",
    examTemplate: "GMP_Exam_Template_2026.pdf",
    answerKey: "GMP_Answer_Key_2026.pdf",
    passingGradeType: "score_10",
    maxAttempts: 3,
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of GMP?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "To increase production speed", isCorrect: false },
          { id: "b", text: "To ensure product quality and safety", isCorrect: true },
          { id: "c", text: "To reduce manufacturing costs", isCorrect: false },
          { id: "d", text: "To improve employee satisfaction", isCorrect: false },
        ],
      },
    ],
    createdBy: "Admin",
    createdAt: "15/01/2026",
    updatedAt: "20/01/2026",
  },
  {
    id: "2",
    trainingId: "TRN-2026-002",
    title: "Cleanroom Qualification",
    description:
      "Training on cleanroom classification, gowning procedures, and environmental monitoring requirements.",
    type: "Technical",
    trainingMethod: "Read & Understood",
    status: "Pending Approval",
    instructor: "Michael Chen",
    instructorType: "internal",
    scheduledDate: "20/03/2026",
    duration: 2,
    location: "Cleanroom Facility",
    capacity: 15,
    enrolled: 15,
    department: "Production",
    mandatory: true,
    passScore: 100,
    version: "v1.0",
    recurrence: { enabled: false, intervalMonths: 0, warningPeriodDays: 0 },
    linkedDocumentId: "DOC-002",
    linkedDocumentTitle: "SOP-CR-002: Cleanroom Operations",
    trainingFiles: [
      {
        id: "tf-004",
        file: null as any,
        name: "Cleanroom_SOP_Manual.pdf",
        size: 3456789,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction:
      "Pay special attention to gowning procedures in Section 3 and environmental monitoring protocols in Section 5.",
    passingGradeType: "pass_fail",
    maxAttempts: 1,
    questions: [],
    createdBy: "QA Manager",
    createdAt: "10/01/2026",
    updatedAt: "25/01/2026",
  },
  {
    id: "3",
    trainingId: "TRN-2026-003",
    title: "Emergency Response Procedures",
    description:
      "Training on fire safety, chemical spill response, and emergency evacuation procedures aligned with OSHA guidelines.",
    type: "Safety",
    trainingMethod: "Hands-on/OJT",
    status: "Effective",
    instructor: "Robert Lee",
    instructorType: "external",
    scheduledDate: "20/01/2026",
    duration: 6,
    location: "[Zoom] https://zoom.us/j/987654321",
    capacity: 50,
    enrolled: 45,
    department: "All Departments",
    mandatory: true,
    passScore: 70,
    version: "v1.0",
    recurrence: { enabled: true, intervalMonths: 6, warningPeriodDays: 30 },
    linkedDocumentId: "DOC-003",
    linkedDocumentTitle: "SOP-HSE-001: Emergency Response Plan",
    trainingFiles: [
      {
        id: "tf-005",
        file: null as any,
        name: "Emergency_Response_Guide.pdf",
        size: 4567890,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction: "Complete all fire extinguisher drills during hands-on session.",
    questions: [],
    createdBy: "HSE Manager",
    createdAt: "05/01/2026",
    updatedAt: "21/01/2026",
  },
];

// --- Mock Data ---
export const MOCK_TRAININGS: TrainingRecord[] = [
  {
    id: "1",
    trainingId: "TRN-2026-001",
    title: "GMP Basic Principles",
    description: "Introduction to Good Manufacturing Practices",
    type: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Effective",
    instructor: "John Smith",
    scheduledDate: "15/02/2026",
    duration: 4,
    location: "Training Room A",
    capacity: 30,
    enrolled: 25,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 80,
    version: "v1.0",
    recurrence: { enabled: true, intervalMonths: 12, warningPeriodDays: 30 },
    createdBy: "Admin",
    createdAt: "15/01/2026",
    updatedAt: "20/01/2026",
  },
  {
    id: "2",
    trainingId: "TRN-2026-002",
    title: "Cleanroom Qualification",
    description: "Training on cleanroom operations and aseptic techniques",
    type: "Technical",
    trainingMethod: "Hands-on/OJT",
    status: "Pending Review",
    instructor: "Sarah Johnson",
    scheduledDate: "26/01/2026",
    duration: 3,
    location: "Cleanroom B",
    capacity: 20,
    enrolled: 20,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 85,
    version: "v1.0",
    recurrence: { enabled: false, intervalMonths: 0, warningPeriodDays: 0 },
    createdBy: "QA Manager",
    createdAt: "10/01/2026",
    updatedAt: "25/01/2026",
  },
  {
    id: "3",
    trainingId: "TRN-2026-003",
    title: "HPLC Operation Advanced",
    description: "Advanced techniques for HPLC operation and troubleshooting",
    type: "Technical",
    trainingMethod: "Hands-on/OJT",
    status: "Pending Approval",
    instructor: "Dr. Michael Chen",
    scheduledDate: "20/01/2026",
    duration: 6,
    location: "Laboratory 2",
    capacity: 15,
    enrolled: 14,
    department: "QC Lab",
    mandatory: false,
    passScore: 75,
    version: "v1.0",
    recurrence: { enabled: true, intervalMonths: 24, warningPeriodDays: 60 },
    createdBy: "Lab Supervisor",
    createdAt: "05/01/2026",
    updatedAt: "21/01/2026",
  },
  {
    id: "4",
    trainingId: "TRN-2026-004",
    title: "ISO 9001:2015 Requirements",
    description:
      "Understanding ISO 9001 quality management system requirements",
    type: "Compliance",
    trainingMethod: "Read & Understood",
    status: "Draft",
    instructor: "Emma Wilson",
    scheduledDate: "01/03/2026",
    duration: 8,
    location: "Conference Hall",
    capacity: 40,
    enrolled: 15,
    department: "All Departments",
    mandatory: false,
    passScore: 70,
    version: "v1.0",
    createdBy: "QA Director",
    createdAt: "15/01/2026",
    updatedAt: "23/01/2026",
  },
  {
    id: "5",
    trainingId: "TRN-2026-005",
    title: "SOP Review & Update Procedures",
    description: "Training on proper SOP review and revision processes",
    type: "SOP",
    trainingMethod: "Read & Understood",
    status: "Obsoleted",
    instructor: "David Brown",
    scheduledDate: "10/01/2026",
    duration: 2,
    location: "Meeting Room 3",
    capacity: 25,
    enrolled: 18,
    department: "Documentation",
    mandatory: true,
    passScore: 80,
    version: "v1.1",
    createdBy: "Doc Control",
    createdAt: "20/12/2025",
    updatedAt: "05/01/2026",
  },
  {
    id: "6",
    trainingId: "TRN-2026-006",
    title: "ISO 14001 Environmental Management",
    description: "Environmental management system fundamentals and auditing",
    type: "Compliance",
    trainingMethod: "Read & Understood",
    status: "Pending Approval",
    instructor: "Kevin Tran",
    scheduledDate: "18/02/2026",
    duration: 4,
    location: "Conference Hall",
    capacity: 35,
    enrolled: 28,
    department: "HSE",
    mandatory: true,
    passScore: 100,
    version: "v1.0",
    createdBy: "HSE Manager",
    createdAt: "20/01/2026",
    updatedAt: "10/02/2026",
  },
  {
    id: "7",
    trainingId: "TRN-2026-007",
    title: "Deviation & Non-Conformance Handling",
    description: "Proper procedures for deviation reporting and resolution",
    type: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Pending Review",
    instructor: "Alice Pham",
    scheduledDate: "20/02/2026",
    duration: 3,
    location: "Training Room B",
    capacity: 25,
    enrolled: 22,
    department: "Quality Assurance",
    mandatory: true,
    passScore: 80,
    version: "v2.1",
    createdBy: "QA Supervisor",
    createdAt: "25/01/2026",
    updatedAt: "05/02/2026",
  },
  {
    id: "8",
    trainingId: "TRN-2026-008",
    title: "Equipment Calibration Procedures",
    description: "Standard procedures for equipment calibration and verification",
    type: "Technical",
    trainingMethod: "Hands-on/OJT",
    status: "Effective",
    instructor: "Dr. Michael Chen",
    scheduledDate: "10/02/2026",
    duration: 5,
    location: "Calibration Lab",
    capacity: 12,
    enrolled: 10,
    department: "QC Lab",
    mandatory: false,
    passScore: 85,
    version: "v3.0",
    createdBy: "Lab Manager",
    createdAt: "08/01/2026",
    updatedAt: "01/02/2026",
  },
  {
    id: "9",
    trainingId: "TRN-2026-009",
    title: "Chemical Safety & Hazard Communication",
    description: "Safe handling of chemicals and GHS labeling requirements",
    type: "Safety",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Draft",
    instructor: "Kevin Tran",
    scheduledDate: "05/03/2026",
    duration: 3,
    location: "Training Room A",
    capacity: 40,
    enrolled: 10,
    department: "All Departments",
    mandatory: true,
    passScore: 75,
    version: "v2.0",
    createdBy: "HSE Manager",
    createdAt: "01/02/2026",
    updatedAt: "05/02/2026",
  },
  {
    id: "10",
    trainingId: "TRN-2026-010",
    title: "Data Integrity in GxP Systems",
    description: "ALCOA+ principles and data integrity requirements",
    type: "Compliance",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Pending Review",
    instructor: "Emma Wilson",
    scheduledDate: "25/02/2026",
    duration: 4,
    location: "Conference Hall",
    capacity: 50,
    enrolled: 35,
    department: "All Departments",
    mandatory: true,
    passScore: 80,
    version: "v1.5",
    createdBy: "QA Director",
    createdAt: "28/01/2026",
    updatedAt: "12/02/2026",
  },
  {
    id: "11",
    trainingId: "TRN-2026-011",
    title: "Batch Record Review",
    description: "Procedures for reviewing and approving batch production records",
    type: "GMP",
    trainingMethod: "Read & Understood",
    status: "Effective",
    instructor: "John Smith",
    scheduledDate: "15/01/2026",
    duration: 2,
    location: "Meeting Room 2",
    capacity: 20,
    enrolled: 18,
    department: "Production",
    mandatory: true,
    passScore: 100,
    version: "v1.2",
    createdBy: "Production Manager",
    createdAt: "15/12/2025",
    updatedAt: "10/01/2026",
  },
  {
    id: "12",
    trainingId: "TRN-2026-012",
    title: "Stability Testing Methods",
    description: "ICH guidelines for stability testing of pharmaceutical products",
    type: "Technical",
    trainingMethod: "Quiz (Paper-based/Manual)",
    status: "Pending Approval",
    instructor: "Sarah Johnson",
    scheduledDate: "22/02/2026",
    duration: 6,
    location: "Laboratory 1",
    capacity: 15,
    enrolled: 12,
    department: "QC Lab",
    mandatory: false,
    passScore: 85,
    version: "v2.0",
    createdBy: "Lab Supervisor",
    createdAt: "18/01/2026",
    updatedAt: "08/02/2026",
  },
];

// --- Mock Data for ApprovalDetailView ---
export const MOCK_APPROVAL_DETAILS: CourseApproval[] = [
  {
    id: "CA-001",
    courseId: "1",
    trainingId: "TRN-2026-001",
    courseTitle: "GMP Basic Principles",
    relatedDocument: "SOP-QA-001: Good Manufacturing Practices",
    relatedDocumentId: "DOC-001",
    trainingType: "GMP",
    trainingMethod: "Quiz (Paper-based/Manual)",
    instructorType: "internal",
    submittedBy: "John Smith",
    submittedAt: "10/02/2026",
    department: "Quality Assurance",
    approvalStatus: "Pending Review",
    passScore: 80,
    version: "v1.0",
    description: "This comprehensive training covers the fundamental principles of Good Manufacturing Practice (GMP) required for all personnel working in pharmaceutical manufacturing environments.",
    instructor: "Dr. Sarah Williams",
    duration: 4,
    location: "Training Room A",
    scheduledDate: "15/03/2026",
    capacity: 25,
    recurrence: { enabled: true, intervalMonths: 12, warningPeriodDays: 30 },
    trainingFiles: MOCK_TRAINING_FILES,
    instruction: "Focus on Chapter 3 (Cleaning Validation) and Appendix B (Equipment Handling). Review all SOPs referenced in Section 2.4 before the training session.",
    examTemplate: "GMP_Exam_Template_2026.pdf",
    answerKey: "GMP_Answer_Key_2026.pdf",
    passingGradeType: "score_10",
    maxAttempts: 3,
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of GMP?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "To increase production speed", isCorrect: false },
          { id: "b", text: "To ensure product quality and safety", isCorrect: true },
          { id: "c", text: "To reduce manufacturing costs", isCorrect: false },
          { id: "d", text: "To improve employee satisfaction", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which document defines the standard operating procedures for cleanroom entry?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "SOP-QA-001", isCorrect: false },
          { id: "b", text: "SOP-CR-002", isCorrect: true },
          { id: "c", text: "SOP-PR-003", isCorrect: false },
          { id: "d", text: "SOP-IT-004", isCorrect: false },
        ],
      },
      {
        id: "q3",
        text: "How often should GMP training be renewed?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "Every 6 months", isCorrect: false },
          { id: "b", text: "Every year", isCorrect: true },
          { id: "c", text: "Every 2 years", isCorrect: false },
          { id: "d", text: "Only once at onboarding", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-002",
    courseId: "2",
    trainingId: "TRN-2026-006",
    courseTitle: "Cleanroom Qualification",
    relatedDocument: "SOP-CR-002: Cleanroom Operations",
    relatedDocumentId: "DOC-002",
    trainingType: "SOP",
    trainingMethod: "Read & Understood",
    instructorType: "internal",
    submittedBy: "Sarah Johnson",
    submittedAt: "12/02/2026",
    department: "Production",
    approvalStatus: "Pending Review",
    passScore: 100,
    version: "v1.0",
    description: "Training on cleanroom classification, gowning procedures, and environmental monitoring requirements.",
    instructor: "Michael Chen",
    duration: 2,
    location: "Cleanroom Facility",
    scheduledDate: "20/03/2026",
    capacity: 15,
    distributionList: ["Production", "Quality Control"],
    recurrence: { enabled: false, intervalMonths: 0, warningPeriodDays: 0 },
    trainingFiles: [
      {
        id: "tf-004",
        file: null as any,
        name: "Cleanroom_SOP_Manual.pdf",
        size: 3456789,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction: "Pay special attention to gowning procedures in Section 3 and environmental monitoring protocols in Section 5.",
    passingGradeType: "pass_fail",
    maxAttempts: 1,
    questions: [],
  },
  {
    id: "CA-003",
    courseId: "3",
    trainingId: "TRN-2026-007",
    courseTitle: "HPLC Operation Advanced",
    relatedDocument: "SOP-LAB-005: HPLC Standard Method",
    relatedDocumentId: "DOC-003",
    trainingType: "Technical",
    trainingMethod: "Quiz (Paper-based/Manual)",
    instructorType: "external",
    submittedBy: "Dr. Michael Chen",
    submittedAt: "08/02/2026",
    department: "QC Lab",
    approvalStatus: "Pending Approval",
    passScore: 85,
    version: "v1.0",
    description: "Advanced HPLC operation training covering method development, troubleshooting, and maintenance procedures.",
    instructor: "Dr. Emily Parker",
    duration: 8,
    location: "QC Laboratory",
    scheduledDate: "25/03/2026",
    capacity: 10,
    distributionList: ["QC Lab", "R&D"],
    recurrence: { enabled: true, intervalMonths: 24, warningPeriodDays: 60 },
    trainingFiles: [
      {
        id: "tf-005",
        file: null as any,
        name: "HPLC_Advanced_Training.pdf",
        size: 5678901,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
      {
        id: "tf-006",
        file: null as any,
        name: "HPLC_Troubleshooting_Guide.pdf",
        size: 2345678,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    instruction: "Review Chapter 4 (Method Development) and practice troubleshooting scenarios in Appendix C before the hands-on session.",
    examTemplate: "HPLC_Exam_2026.pdf",
    answerKey: "HPLC_Answer_Key_2026.pdf",
    passingGradeType: "percentage",
    maxAttempts: 2,
    questions: [
      {
        id: "q1",
        text: "What is the recommended mobile phase flow rate for analytical HPLC?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "0.1 mL/min", isCorrect: false },
          { id: "b", text: "1.0 mL/min", isCorrect: true },
          { id: "c", text: "5.0 mL/min", isCorrect: false },
          { id: "d", text: "10.0 mL/min", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which detector is most commonly used for UV-absorbing compounds?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "DAD/PDA detector", isCorrect: true },
          { id: "b", text: "Refractive Index detector", isCorrect: false },
          { id: "c", text: "Fluorescence detector", isCorrect: false },
          { id: "d", text: "Conductivity detector", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-006",
    courseId: "6",
    trainingId: "TRN-2026-011",
    courseTitle: "ISO 14001 Environmental Management",
    relatedDocument: "SOP-ENV-001: Environmental Management System",
    relatedDocumentId: "DOC-006",
    trainingType: "Compliance",
    trainingMethod: "Read & Understood",
    instructorType: "internal",
    submittedBy: "Kevin Tran",
    submittedAt: "18/02/2026",
    department: "HSE",
    approvalStatus: "Pending Approval",
    passScore: 100,
    version: "v1.0",
    description: "This training covers the ISO 14001 Environmental Management System requirements, environmental policy, objectives and targets, and compliance monitoring procedures.",
    instructor: "Lisa Nguyen",
    duration: 3,
    location: "HSE Training Center",
    scheduledDate: "28/03/2026",
    capacity: 30,
    distributionList: ["HSE", "Production", "Maintenance"],
    recurrence: { enabled: true, intervalMonths: 12, warningPeriodDays: 30 },
    trainingFiles: [
      {
        id: "tf-007",
        file: null as any,
        name: "ISO14001_Environmental_Management.pdf",
        size: 4567890,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    questions: [],
  },
  {
    id: "CA-008",
    courseId: "7",
    trainingId: "TRN-2026-013",
    courseTitle: "Deviation & Non-Conformance Handling",
    relatedDocument: "SOP-QA-007: Deviation Management",
    relatedDocumentId: "DOC-007",
    trainingType: "Compliance",
    trainingMethod: "Quiz (Paper-based/Manual)",
    instructorType: "internal",
    submittedBy: "Alice Pham",
    submittedAt: "19/02/2026",
    department: "Quality Assurance",
    approvalStatus: "Pending Approval",
    passScore: 80,
    version: "v1.0",
    description: "Training on deviation detection, documentation, investigation, root cause analysis, and CAPA implementation procedures.",
    instructor: "Dr. Sarah Williams",
    duration: 4,
    location: "Training Room B",
    scheduledDate: "01/04/2026",
    capacity: 20,
    distributionList: ["Quality Assurance", "Production", "QC Lab"],
    recurrence: { enabled: true, intervalMonths: 12, warningPeriodDays: 30 },
    trainingFiles: [
      {
        id: "tf-008",
        file: null as any,
        name: "Deviation_Management_SOP.pdf",
        size: 3456789,
        type: "application/pdf",
        progress: 100,
        status: "success",
      },
    ],
    questions: [
      {
        id: "q1",
        text: "What is the first step when a deviation is detected?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "Document and notify QA immediately", isCorrect: true },
          { id: "b", text: "Continue production", isCorrect: false },
          { id: "c", text: "Correct the deviation without reporting", isCorrect: false },
          { id: "d", text: "Wait for the next shift", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "What tool is commonly used for root cause analysis?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "SWOT Analysis", isCorrect: false },
          { id: "b", text: "Fishbone (Ishikawa) Diagram", isCorrect: true },
          { id: "c", text: "Balance Scorecard", isCorrect: false },
          { id: "d", text: "Gantt Chart", isCorrect: false },
        ],
      },
    ],
  },
];

// --- Mock Data for PendingReviewView ---
export const MOCK_PENDING_REVIEWS: CourseApproval[] = [
  {
    id: "CA-001",
    courseId: "1",
    trainingId: "TRN-2026-001",
    courseTitle: "GMP Basic Principles",
    relatedDocument: "SOP-QA-001: Good Manufacturing Practices",
    relatedDocumentId: "DOC-001",
    trainingMethod: "Quiz (Paper-based/Manual)",
    trainingType: "GMP",
    instructor: "John Smith",
    scheduledDate: "01/03/2026",
    capacity: 30,
    enrolled: 25,
    submittedBy: "John Smith",
    submittedAt: "10/02/2026",
    department: "Quality Assurance",
    approvalStatus: "Pending Review",
    passScore: 80,
    version: "v1.0",
    description: "Basic GMP principles for QA department.",
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of GMP?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "To increase production speed", isCorrect: false },
          { id: "b", text: "To ensure product quality and safety", isCorrect: true },
          { id: "c", text: "To reduce manufacturing costs", isCorrect: false },
          { id: "d", text: "To improve employee satisfaction", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which document defines the standard operating procedures for cleanroom entry?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "SOP-QA-001", isCorrect: false },
          { id: "b", text: "SOP-CR-002", isCorrect: true },
          { id: "c", text: "SOP-PR-003", isCorrect: false },
          { id: "d", text: "SOP-IT-004", isCorrect: false },
        ],
      },
      {
        id: "q3",
        text: "How often should GMP training be renewed?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "Every 6 months", isCorrect: false },
          { id: "b", text: "Every year", isCorrect: true },
          { id: "c", text: "Every 2 years", isCorrect: false },
          { id: "d", text: "Only once at onboarding", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-002",
    courseId: "2",
    trainingId: "TRN-2026-006",
    courseTitle: "Cleanroom Qualification",
    relatedDocument: "SOP-CR-002: Cleanroom Operations",
    relatedDocumentId: "DOC-002",
    trainingMethod: "Read & Understood",
    trainingType: "SOP",
    instructor: "Sarah Johnson",
    scheduledDate: "05/03/2026",
    capacity: 20,
    enrolled: 18,
    submittedBy: "Sarah Johnson",
    submittedAt: "12/02/2026",
    department: "Production",
    approvalStatus: "Pending Review",
    passScore: 100,
    version: "v1.0",
    description: "Cleanroom requirements for production personnel.",
    questions: [],
  },
  {
    id: "CA-003",
    courseId: "3",
    trainingId: "TRN-2026-007",
    courseTitle: "HPLC Operation Advanced",
    relatedDocument: "SOP-LAB-005: HPLC Standard Method",
    relatedDocumentId: "DOC-003",
    trainingMethod: "Quiz (Paper-based/Manual)",
    trainingType: "Technical",
    instructor: "Dr. Michael Chen",
    scheduledDate: "10/03/2026",
    capacity: 15,
    enrolled: 12,
    submittedBy: "Dr. Michael Chen",
    submittedAt: "08/02/2026",
    department: "QC Lab",
    approvalStatus: "Pending Review",
    approvedBy: undefined,
    approvedAt: undefined,
    passScore: 85,
    version: "v1.0",
    description: "HPLC Advanced training for QC Lab.",
    questions: [
      {
        id: "q1",
        text: "What is the recommended mobile phase flow rate for analytical HPLC?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "0.1 mL/min", isCorrect: false },
          { id: "b", text: "1.0 mL/min", isCorrect: true },
          { id: "c", text: "5.0 mL/min", isCorrect: false },
          { id: "d", text: "10.0 mL/min", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which detector is most commonly used for UV-absorbing compounds?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "DAD/PDA detector", isCorrect: true },
          { id: "b", text: "Refractive Index detector", isCorrect: false },
          { id: "c", text: "Fluorescence detector", isCorrect: false },
          { id: "d", text: "Conductivity detector", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-004",
    courseId: "4",
    trainingId: "TRN-2026-008",
    courseTitle: "ISO 9001:2015 Requirements",
    relatedDocument: "SOP-QMS-010: Quality Management System",
    relatedDocumentId: "DOC-004",
    trainingMethod: "Quiz (Paper-based/Manual)",
    trainingType: "Compliance",
    instructor: "Emma Wilson",
    scheduledDate: "15/03/2026",
    capacity: 50,
    enrolled: 42,
    submittedBy: "Emma Wilson",
    submittedAt: "15/02/2026",
    department: "All Departments",
    approvalStatus: "Pending Review",
    passScore: 70,
    version: "v1.0",
    description: "ISO 9001:2015 standard requirement training.",
    questions: [
      {
        id: "q1",
        text: "What is the risk-based thinking approach in ISO 9001:2015?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "Eliminating all risks completely", isCorrect: false },
          { id: "b", text: "Identifying and addressing risks that affect conformity", isCorrect: true },
          { id: "c", text: "Only documenting risks", isCorrect: false },
          { id: "d", text: "Avoiding change", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-005",
    courseId: "5",
    trainingId: "TRN-2026-009",
    courseTitle: "SOP Review & Update Procedures",
    relatedDocument: "SOP-DC-003: Document Change Control",
    relatedDocumentId: "DOC-005",
    trainingMethod: "Read & Understood",
    trainingType: "SOP",
    instructor: "David Brown",
    scheduledDate: "20/02/2026",
    capacity: 25,
    enrolled: 10,
    submittedBy: "David Brown",
    submittedAt: "05/02/2026",
    department: "Documentation",
    approvalStatus: "Rejected",
    approvedBy: "QA Manager",
    approvedAt: "06/02/2026",
    rejectionReason: "Training content does not reflect latest SOP revision (Rev.5). Please update to align with SOP-DC-003 Rev.5 effective 01/28/2026.",
    passScore: 80,
    version: "v1.0",
    description: "SOP Review procedures for doc control.",
    questions: [],
  },
];

// --- Mock Data for PendingApprovalView ---
export const MOCK_PENDING_APPROVAL: CourseApproval[] = [
  {
    id: "CA-003",
    courseId: "3",
    trainingId: "TRN-2026-007",
    courseTitle: "HPLC Operation Advanced",
    relatedDocument: "SOP-LAB-005: HPLC Standard Method",
    relatedDocumentId: "DOC-003",
    trainingMethod: "Quiz (Paper-based/Manual)",
    trainingType: "Technical",
    instructor: "Dr. Michael Chen",
    scheduledDate: "10/03/2026",
    capacity: 15,
    enrolled: 12,
    submittedBy: "Dr. Michael Chen",
    submittedAt: "08/02/2026",
    department: "QC Lab",
    approvalStatus: "Pending Approval",
    approvedBy: undefined,
    approvedAt: undefined,
    passScore: 85,
    version: "v1.0",
    description: "Advanced HPLC training approval request.",
    questions: [
      {
        id: "q1",
        text: "What is the recommended mobile phase flow rate for analytical HPLC?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "0.1 mL/min", isCorrect: false },
          { id: "b", text: "1.0 mL/min", isCorrect: true },
          { id: "c", text: "5.0 mL/min", isCorrect: false },
          { id: "d", text: "10.0 mL/min", isCorrect: false },
        ],
      },
      {
        id: "q2",
        text: "Which detector is most commonly used for UV-absorbing compounds?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "DAD/PDA detector", isCorrect: true },
          { id: "b", text: "Refractive Index detector", isCorrect: false },
          { id: "c", text: "Fluorescence detector", isCorrect: false },
          { id: "d", text: "Conductivity detector", isCorrect: false },
        ],
      },
    ],
  },
  {
    id: "CA-006",
    courseId: "6",
    trainingId: "TRN-2026-011",
    courseTitle: "ISO 14001 Environmental Management",
    relatedDocument: "SOP-ENV-001: Environmental Management System",
    relatedDocumentId: "DOC-006",
    trainingMethod: "Read & Understood",
    trainingType: "Compliance",
    instructor: "Kevin Tran",
    scheduledDate: "20/03/2026",
    capacity: 40,
    enrolled: 35,
    submittedBy: "Kevin Tran",
    submittedAt: "18/02/2026",
    department: "HSE",
    approvalStatus: "Pending Approval",
    passScore: 100,
    version: "v1.0",
    description: "ISO 14001 Environmental management training.",
    questions: [],
  },
  {
    id: "CA-008",
    courseId: "7",
    trainingId: "TRN-2026-013",
    courseTitle: "Deviation & Non-Conformance Handling",
    relatedDocument: "SOP-QA-007: Deviation Management",
    relatedDocumentId: "DOC-007",
    trainingMethod: "Quiz (Paper-based/Manual)",
    trainingType: "GMP",
    instructor: "Alice Pham",
    scheduledDate: "25/03/2026",
    capacity: 30,
    enrolled: 22,
    submittedBy: "Alice Pham",
    submittedAt: "19/02/2026",
    department: "Quality Assurance",
    approvalStatus: "Pending Approval",
    passScore: 80,
    version: "v1.0",
    description: "Deviation and Non-Conformance handling procedures.",
    questions: [
      {
        id: "q1",
        text: "What is the first step when a deviation is detected?",
        type: "multiple_choice",
        points: 10,
        options: [
          { id: "a", text: "Document and notify QA immediately", isCorrect: true },
          { id: "b", text: "Continue production", isCorrect: false },
          { id: "c", text: "Correct the deviation without reporting", isCorrect: false },
          { id: "d", text: "Wait for the next shift", isCorrect: false },
        ],
      },
    ],
  },
];

// ─── Course Progress Mock Data ────────────────────────────────────────────────
// TODO: Replace with API call: GET /api/training/courses/:id/progress

export const MOCK_PROGRESS_INFO: CourseProgressInfo = {
  id: "1",
  trainingId: "TRN-2026-001",
  title: "GMP Basic Principles",
  totalEnrolled: 25,
  completed: 15,
  inProgress: 5,
  notStarted: 3,
  overdue: 2,
  passRate: 87,
  averageScore: 8.2,
  passingScore: 7,
  passingGradeType: "score_10",
  dueDate: "2026-04-15",
};

export const MOCK_EMPLOYEE_PROGRESS: EmployeeProgress[] = [
  { userId: "EMP-1001", name: "Nguyen Van An", email: "an.nguyen@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "QA Specialist", enrollmentStatus: "Completed", resultStatus: "Pass", score: 9, completedAt: "2026-02-10", examDate: "2026-02-10", attempts: 1 },
  { userId: "EMP-1002", name: "Tran Thi Binh", email: "binh.tran@company.com", department: "QC Lab", businessUnit: "Quality Unit", jobTitle: "Lab Technician", enrollmentStatus: "Completed", resultStatus: "Pass", score: 8, completedAt: "2026-02-11", examDate: "2026-02-11", attempts: 1 },
  { userId: "EMP-1003", name: "Le Van Cuong", email: "cuong.le@company.com", department: "Production", businessUnit: "Operation Unit", jobTitle: "Production Manager", enrollmentStatus: "Completed", resultStatus: "Fail", score: 5, completedAt: "2026-02-12", examDate: "2026-02-12", attempts: 2 },
  { userId: "EMP-1004", name: "Pham Thi Dung", email: "dung.pham@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "QA Specialist", enrollmentStatus: "Completed", resultStatus: "Pass", score: 10, completedAt: "2026-02-09", examDate: "2026-02-09", attempts: 1 },
  { userId: "EMP-1005", name: "Hoang Van Em", email: "em.hoang@company.com", department: "R&D", businessUnit: "Operation Unit", jobTitle: "R&D Scientist", enrollmentStatus: "In-Progress", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1006", name: "Vo Thi Phuong", email: "phuong.vo@company.com", department: "Production", businessUnit: "Operation Unit", jobTitle: "Production Supervisor", enrollmentStatus: "Completed", resultStatus: "Pass", score: 7, completedAt: "2026-02-13", examDate: "2026-02-13", attempts: 2 },
  { userId: "EMP-1007", name: "Dang Van Gia", email: "gia.dang@company.com", department: "QC Lab", businessUnit: "Quality Unit", jobTitle: "Senior Analyst", enrollmentStatus: "Overdue", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1008", name: "Bui Thi Hanh", email: "hanh.bui@company.com", department: "Engineering", businessUnit: "Operation Unit", jobTitle: "Senior Engineer", enrollmentStatus: "Not Started", resultStatus: "N/A", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1009", name: "Ngo Van Ich", email: "ich.ngo@company.com", department: "Warehouse", businessUnit: "Operation Unit", jobTitle: "Warehouse Supervisor", enrollmentStatus: "Completed", resultStatus: "Pass", score: 8, completedAt: "2026-02-14", examDate: "2026-02-14", attempts: 1 },
  { userId: "EMP-1010", name: "Trinh Thi Kim", email: "kim.trinh@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "QA Manager", enrollmentStatus: "Completed", resultStatus: "Pass", score: 9, completedAt: "2026-02-08", examDate: "2026-02-08", attempts: 1 },
  { userId: "EMP-1011", name: "Do Van Lam", email: "lam.do@company.com", department: "Production", businessUnit: "Operation Unit", jobTitle: "Operator", enrollmentStatus: "In-Progress", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1012", name: "Ly Thi Mai", email: "mai.ly@company.com", department: "R&D", businessUnit: "Operation Unit", jobTitle: "Research Associate", enrollmentStatus: "Completed", resultStatus: "Pass", score: 8, completedAt: "2026-02-15", examDate: "2026-02-15", attempts: 1 },
  { userId: "EMP-1013", name: "Truong Van Nam", email: "nam.truong@company.com", department: "Engineering", businessUnit: "Operation Unit", jobTitle: "Maintenance Technician", enrollmentStatus: "Not Started", resultStatus: "N/A", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1014", name: "Huynh Thi Oanh", email: "oanh.huynh@company.com", department: "QC Lab", businessUnit: "Quality Unit", jobTitle: "Lab Supervisor", enrollmentStatus: "Completed", resultStatus: "Pass", score: 9, completedAt: "2026-02-10", examDate: "2026-02-10", attempts: 1 },
  { userId: "EMP-1015", name: "Phan Van Phuc", email: "phuc.phan@company.com", department: "Warehouse", businessUnit: "Operation Unit", jobTitle: "Logistics Coordinator", enrollmentStatus: "In-Progress", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1016", name: "Duong Thi Quynh", email: "quynh.duong@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "Document Controller", enrollmentStatus: "Completed", resultStatus: "Pass", score: 8, completedAt: "2026-02-12", examDate: "2026-02-12", attempts: 1 },
  { userId: "EMP-1017", name: "Cao Van Rang", email: "rang.cao@company.com", department: "Production", businessUnit: "Operation Unit", jobTitle: "Operator", enrollmentStatus: "Overdue", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1018", name: "Ta Thi Son", email: "son.ta@company.com", department: "Engineering", businessUnit: "Operation Unit", jobTitle: "Calibration Technician", enrollmentStatus: "Completed", resultStatus: "Pass", score: 7, completedAt: "2026-02-16", examDate: "2026-02-16", attempts: 3 },
  { userId: "EMP-1019", name: "Mai Van Tuan", email: "tuan.mai@company.com", department: "QC Lab", businessUnit: "Quality Unit", jobTitle: "Microbiologist", enrollmentStatus: "In-Progress", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1020", name: "Luu Thi Uyen", email: "uyen.luu@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "QA Specialist", enrollmentStatus: "Completed", resultStatus: "Pass", score: 10, completedAt: "2026-02-09", examDate: "2026-02-09", attempts: 1 },
  { userId: "EMP-1021", name: "Dinh Van Vinh", email: "vinh.dinh@company.com", department: "Production", businessUnit: "Operation Unit", jobTitle: "Shift Leader", enrollmentStatus: "Completed", resultStatus: "Pass", score: 8, completedAt: "2026-02-17", examDate: "2026-02-17", attempts: 1 },
  { userId: "EMP-1022", name: "Ha Thi Xuan", email: "xuan.ha@company.com", department: "R&D", businessUnit: "Operation Unit", jobTitle: "Formulation Scientist", enrollmentStatus: "Not Started", resultStatus: "N/A", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1023", name: "Tong Van Yen", email: "yen.tong@company.com", department: "Warehouse", businessUnit: "Operation Unit", jobTitle: "Receiving Inspector", enrollmentStatus: "In-Progress", resultStatus: "Pending", score: null, completedAt: null, examDate: null, attempts: 0 },
  { userId: "EMP-1024", name: "Chu Thi Zen", email: "zen.chu@company.com", department: "Engineering", businessUnit: "Operation Unit", jobTitle: "Process Engineer", enrollmentStatus: "Completed", resultStatus: "Pass", score: 9, completedAt: "2026-02-18", examDate: "2026-02-18", attempts: 1 },
  { userId: "EMP-1025", name: "Lam Van Anh", email: "anh.lam@company.com", department: "QA", businessUnit: "Quality Unit", jobTitle: "Validation Specialist", enrollmentStatus: "Exempt", resultStatus: "N/A", score: null, completedAt: null, examDate: null, attempts: 0 },
];
