import { Supplier } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_SUPPLIERS: Supplier[] = [
  {
    id: "1",
    supplierId: "SUP-001",
    name: "PharmaChem AG",
    category: "API Manufacturer",
    status: "Qualified",
    riskRating: "Low",
    country: "Switzerland",
    city: "Basel",
    contactPerson: "Dr. Stefan Hoffmann",
    email: "s.hoffmann@pharmachem.ch",
    phone: "+41 61 555 0100",
    qualificationDate: "15/03/2024",
    lastAuditDate: "20/09/2025",
    nextAuditDate: "20/09/2026",
    suppliedMaterials: ["Amoxicillin Trihydrate", "Cephalexin"],
    gmpCertificate: "GMP-CH-2025-001",
    qualityAgreement: true,
    responsiblePerson: "QA Director",
    createdAt: "15/03/2024, 10:00:00",
    updatedAt: "01/12/2025, 09:00:00",
  },
  {
    id: "2",
    supplierId: "SUP-002",
    name: "PackSolutions GmbH",
    category: "Packaging Material",
    status: "Qualified",
    riskRating: "Low",
    country: "Germany",
    city: "Munich",
    contactPerson: "Ingrid Bauer",
    email: "i.bauer@packsolutions.de",
    phone: "+49 89 555 0200",
    qualificationDate: "10/06/2023",
    lastAuditDate: "10/06/2025",
    nextAuditDate: "10/06/2026",
    suppliedMaterials: ["PVC/Alu Blisters", "Cartons", "Labels"],
    qualityAgreement: true,
    responsiblePerson: "Procurement Manager",
    createdAt: "10/06/2023, 08:00:00",
    updatedAt: "15/11/2025, 14:30:00",
  },
  {
    id: "3",
    supplierId: "SUP-003",
    name: "BioTest Labs S.r.l.",
    category: "Laboratory Service",
    status: "Under Evaluation",
    riskRating: "Medium",
    country: "Italy",
    city: "Milan",
    contactPerson: "Dr. Marco Rossi",
    email: "m.rossi@biotestlabs.it",
    phone: "+39 02 555 0300",
    suppliedMaterials: ["Microbial Testing", "Endotoxin Testing"],
    qualityAgreement: false,
    responsiblePerson: "QC Director",
    createdAt: "10/01/2026, 09:00:00",
    updatedAt: "20/01/2026, 11:00:00",
  },
  {
    id: "4",
    supplierId: "SUP-004",
    name: "Excipi Corp",
    category: "Excipient Supplier",
    status: "Conditionally Approved",
    riskRating: "Medium",
    country: "France",
    city: "Lyon",
    contactPerson: "Pierre Dubois",
    email: "p.dubois@excipicorp.fr",
    phone: "+33 4 555 0400",
    qualificationDate: "20/08/2025",
    lastAuditDate: "15/08/2025",
    nextAuditDate: "15/02/2026",
    suppliedMaterials: ["Lactose Monohydrate", "Microcrystalline Cellulose", "Magnesium Stearate"],
    gmpCertificate: "GMP-FR-2025-042",
    qualityAgreement: true,
    responsiblePerson: "QA Manager",
    createdAt: "20/08/2025, 10:00:00",
    updatedAt: "15/01/2026, 09:00:00",
  },
  {
    id: "5",
    supplierId: "SUP-005",
    name: "ColdTrans Logistics B.V.",
    category: "Logistics Provider",
    status: "Suspended",
    riskRating: "High",
    country: "Netherlands",
    city: "Rotterdam",
    contactPerson: "Jan van der Berg",
    email: "j.vanderberg@coldtrans.nl",
    phone: "+31 10 555 0500",
    qualificationDate: "20/01/2023",
    lastAuditDate: "10/07/2025",
    nextAuditDate: "10/01/2026",
    suppliedMaterials: ["Cold Chain Distribution", "GDP Transport"],
    gdpCertificate: "GDP-NL-2024-078",
    qualityAgreement: true,
    responsiblePerson: "Supply Chain Director",
    createdAt: "20/01/2023, 10:00:00",
    updatedAt: "12/01/2026, 08:00:00",
  },
];
