import { ChangeControl } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_CHANGES: ChangeControl[] = [
  {
    id: "1",
    changeId: "CC-2026-001",
    title: "Tablet Compression Force Adjustment",
    description: "Increase compression force from 15kN to 18kN for improved tablet hardness",
    type: "Process Change",
    impact: "Medium",
    status: "Impact Assessment",
    initiatedBy: "Dr. Hans Mueller",
    initiatedDate: "20/01/2026",
    department: "Production",
    reason: "Tablet hardness below specification for batch TAB-2026-010",
    proposedChange: "Adjust compression parameters and validate with 3 production batches",
    affectedSystems: ["Tablet Press #3", "Batch Record SOP-PRD-045"],
    targetDate: "15/03/2026",
    assignedTo: "Process Engineer Team",
    reviewer: "QA Manager",
    createdAt: "20/01/2026, 09:00:00",
    updatedAt: "25/01/2026, 14:30:00",
  },
  {
    id: "2",
    changeId: "CC-2026-002",
    title: "HPLC Column Change - Dissolution Method",
    description: "Replace C18 column with C8 column for improved peak resolution",
    type: "Analytical Method",
    impact: "High",
    status: "Pending Approval",
    initiatedBy: "Dr. Sarah Chen",
    initiatedDate: "18/01/2026",
    department: "QC Laboratory",
    reason: "Current method shows co-eluting peaks affecting accuracy",
    proposedChange: "Validate new column with method transfer protocol",
    regulatoryImpact: "Method updates require filing Type IA variation",
    targetDate: "28/02/2026",
    assignedTo: "QC Analytical Team",
    reviewer: "QC Director",
    approver: "QA Director",
    createdAt: "18/01/2026, 11:00:00",
    updatedAt: "24/01/2026, 09:15:00",
  },
  {
    id: "3",
    changeId: "CC-2026-003",
    title: "Raw Material Supplier Change - Lactose Monohydrate",
    description: "Qualify alternative supplier for lactose monohydrate excipient",
    type: "Material Change",
    impact: "High",
    status: "Submitted",
    initiatedBy: "Procurement Manager",
    initiatedDate: "22/01/2026",
    department: "Supply Chain",
    reason: "Current supplier facing capacity constraints; risk of supply disruption",
    proposedChange: "Qualify AltSupplier GmbH with comparability study",
    regulatoryImpact: "Type IB variation required for EU markets",
    targetDate: "30/04/2026",
    assignedTo: "QA/QC Team",
    createdAt: "22/01/2026, 08:30:00",
    updatedAt: "23/01/2026, 10:00:00",
  },
  {
    id: "4",
    changeId: "CC-2025-098",
    title: "Cleanroom HVAC Upgrade - Area B",
    description: "Upgrade HVAC system to improve air change rate to 20 ACH",
    type: "Facility Change",
    impact: "High",
    status: "Closed",
    initiatedBy: "Facility Manager",
    initiatedDate: "15/10/2025",
    department: "Engineering",
    reason: "Air change rate below EU-GMP Grade C requirements during peak summer",
    proposedChange: "Install additional AHU units and revalidate cleanroom classification",
    targetDate: "31/12/2025",
    actualCompletionDate: "20/12/2025",
    assignedTo: "Engineering Team",
    reviewer: "QA Manager",
    approver: "Site Director",
    createdAt: "15/10/2025, 10:00:00",
    updatedAt: "20/12/2025, 16:30:00",
  },
  {
    id: "5",
    changeId: "CC-2026-004",
    title: "Equipment Cleaning Procedure Update - Mixer",
    description: "Update cleaning SOP for high-shear granulator to include rinse sampling",
    type: "Cleaning Procedure",
    impact: "Medium",
    status: "Implementation",
    initiatedBy: "Validation Manager",
    initiatedDate: "10/01/2026",
    department: "Production",
    reason: "Cleaning validation showed residue carryover at sampling point #3",
    proposedChange: "Add intermediate rinse step and update acceptance criteria",
    targetDate: "15/02/2026",
    assignedTo: "Validation Team",
    reviewer: "Production Manager",
    createdAt: "10/01/2026, 14:00:00",
    updatedAt: "26/01/2026, 11:45:00",
  },
];
