import { Deviation } from "./types";

// Mock Data
export const MOCK_DEVIATIONS: Deviation[] = [
  {
    id: "1",
    deviationId: "DEV-2026-001",
    title: "Temperature Excursion in Cold Storage",
    description:
      "Temperature exceeded 8°C for 45 minutes in cold storage area B",
    category: "Environmental",
    severity: "Major",
    status: "Under Investigation",
    reportedBy: "John Smith",
    reportedDate: "24/01/2026",
    department: "Warehouse",
    affectedProduct: "Vaccine Lot ABC-123",
    affectedBatch: "BATCH-2026-001",
    immediateAction:
      "Product moved to backup cold storage, temperature monitoring increased",
    investigationDeadline: "31/01/2026",
    assignedTo: "Dr. Sarah Johnson",
    createdAt: "24/01/2026, 08:30:00",
    updatedAt: "25/01/2026, 10:15:00",
  },
  {
    id: "2",
    deviationId: "DEV-2026-002",
    title: "Out of Specification Test Result",
    description: "Dissolution test failed for tablet batch",
    category: "Product Quality",
    severity: "Critical",
    status: "Pending Review",
    reportedBy: "Mike Chen",
    reportedDate: "23/01/2026",
    department: "QC Lab",
    affectedProduct: "Aspirin 500mg Tablets",
    affectedBatch: "TAB-2026-005",
    immediateAction: "Batch quarantined, retesting initiated",
    rootCause: "Granulation moisture content out of range",
    investigationDeadline: "30/01/2026",
    assignedTo: "Dr. Emma Wilson",
    reviewer: "QA Manager",
    createdAt: "23/01/2026, 14:20:00",
    updatedAt: "25/01/2026, 09:45:00",
  },
  {
    id: "3",
    deviationId: "DEV-2026-003",
    title: "Equipment Malfunction - Tablet Press",
    description: "Tablet press #3 stopped during production run",
    category: "Equipment",
    severity: "Major",
    status: "Closed",
    reportedBy: "David Brown",
    reportedDate: "15/01/2026",
    department: "Production",
    affectedBatch: "TAB-2026-003",
    immediateAction: "Production switched to tablet press #2",
    rootCause: "Worn compression rollers",
    correctiveAction:
      "Rollers replaced and preventive maintenance schedule updated",
    preventiveAction:
      "Implement weekly inspection checklist for all tablet presses",
    investigationDeadline: "20/01/2026",
    assignedTo: "Maintenance Team",
    reviewer: "Production Manager",
    approver: "QA Director",
    closedDate: "22/01/2026",
    createdAt: "15/01/2026, 11:00:00",
    updatedAt: "22/01/2026, 16:30:00",
  },
  {
    id: "4",
    deviationId: "DEV-2026-004",
    title: "Raw Material Receipt Discrepancy",
    description: "COA missing for raw material shipment",
    category: "Material",
    severity: "Minor",
    status: "Open",
    reportedBy: "Lisa Anderson",
    reportedDate: "25/01/2026",
    department: "Warehouse",
    immediateAction: "Material quarantined pending COA receipt",
    investigationDeadline: "01/02/2026",
    assignedTo: "Procurement Team",
    createdAt: "25/01/2026, 13:15:00",
    updatedAt: "25/01/2026, 13:15:00",
  },
  {
    id: "5",
    deviationId: "DEV-2025-098",
    title: "Incomplete Batch Record",
    description: "Missing operator signature on cleaning verification form",
    category: "Documentation",
    severity: "Minor",
    status: "Closed",
    reportedBy: "Tom Wilson",
    reportedDate: "20/12/2025",
    department: "Production",
    affectedBatch: "SYR-2025-099",
    immediateAction: "Operator located and signature obtained",
    rootCause: "Operator forgot to sign after cleaning completion",
    correctiveAction: "Training provided on GMP documentation requirements",
    preventiveAction: "Implement end-of-shift document checklist",
    investigationDeadline: "27/12/2025",
    assignedTo: "Production Supervisor",
    reviewer: "QA Manager",
    approver: "QA Director",
    closedDate: "30/12/2025",
    createdAt: "20/12/2025, 15:45:00",
    updatedAt: "30/12/2025, 10:00:00",
  },
];
