import { RegulatorySubmission } from "./types";

// ============================================================================
// MOCK DATA
// ============================================================================
export const MOCK_SUBMISSIONS: RegulatorySubmission[] = [
  {
    id: "1",
    submissionId: "REG-2026-001",
    title: "Type II Variation - Amoxicillin Manufacturing Process",
    description: "Update manufacturing process parameters for tablet compression",
    type: "Type II Variation",
    status: "Submitted",
    authority: "EMA",
    relatedProduct: "Amoxicillin Capsules 500mg",
    submissionDate: "15/01/2026",
    targetDate: "15/07/2026",
    referenceNumber: "EMA/2026/VAR-II/001",
    submittedBy: "Dr. Elena Vasquez",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "3.2",
    ctdModule: "Module 3 - Quality",
    createdAt: "10/01/2026, 09:00:00",
    updatedAt: "15/01/2026, 14:30:00",
  },
  {
    id: "2",
    submissionId: "REG-2026-002",
    title: "GMP Certificate Renewal - Site A",
    description: "Annual GMP certificate renewal for manufacturing site A",
    type: "GMP Certificate",
    status: "Under Review",
    authority: "BfArM",
    submissionDate: "05/01/2026",
    targetDate: "05/04/2026",
    referenceNumber: "BfArM/2026/GMP/045",
    submittedBy: "QA Director",
    department: "Quality Assurance",
    assignedTo: "QA Director",
    reviewer: "Site Director",
    createdAt: "05/01/2026, 10:00:00",
    updatedAt: "20/01/2026, 11:00:00",
  },
  {
    id: "3",
    submissionId: "REG-2026-003",
    title: "PSUR/PBRER - Metformin HCl Tablets",
    description: "Periodic Safety Update Report for marketing authorization renewal",
    type: "PSUR/PBRER",
    status: "Draft",
    authority: "EMA",
    relatedProduct: "Metformin HCl Tablets 850mg",
    targetDate: "31/03/2026",
    submittedBy: "PV Manager",
    department: "Pharmacovigilance",
    assignedTo: "PV Analyst",
    dossierVersion: "1.0",
    ctdModule: "Module 5 - Clinical",
    createdAt: "20/01/2026, 08:00:00",
    updatedAt: "25/01/2026, 09:00:00",
  },
  {
    id: "4",
    submissionId: "REG-2025-045",
    title: "Marketing Authorization Application - Omeprazole DR Capsules",
    description: "New MAA submission for omeprazole delayed-release capsules 20mg",
    type: "Marketing Authorization Application",
    status: "Approved",
    authority: "EMA",
    relatedProduct: "Omeprazole DR Capsules 20mg",
    submissionDate: "15/03/2025",
    targetDate: "15/12/2025",
    approvalDate: "28/11/2025",
    referenceNumber: "EMA/2025/MAA/098",
    submittedBy: "Dr. Hans Mueller",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "1.0",
    ctdModule: "Modules 1-5",
    createdAt: "01/03/2025, 10:00:00",
    updatedAt: "28/11/2025, 16:00:00",
  },
  {
    id: "5",
    submissionId: "REG-2026-004",
    title: "Type IA Variation - Updated Shelf Life for Ceftriaxone",
    description: "Extend shelf life from 24 to 36 months based on stability data",
    type: "Type IA Variation",
    status: "Questions Received",
    authority: "MHRA",
    relatedProduct: "Ceftriaxone for Injection 1g",
    submissionDate: "10/12/2025",
    targetDate: "10/03/2026",
    referenceNumber: "MHRA/2025/VAR-IA/112",
    submittedBy: "RA Specialist",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "2.1",
    ctdModule: "Module 3 - Quality",
    createdAt: "05/12/2025, 09:00:00",
    updatedAt: "22/01/2026, 08:00:00",
  },
  {
    id: "6",
    submissionId: "REG-2025-038",
    title: "Renewal - Amoxicillin Marketing Authorization",
    description: "5-year renewal of marketing authorization for EU market",
    type: "Renewal",
    status: "Approved",
    authority: "EMA",
    relatedProduct: "Amoxicillin Capsules 500mg",
    submissionDate: "01/06/2025",
    targetDate: "01/10/2025",
    approvalDate: "15/09/2025",
    referenceNumber: "EMA/2025/REN/067",
    submittedBy: "Dr. Elena Vasquez",
    department: "Regulatory Affairs",
    assignedTo: "RA Team Lead",
    reviewer: "RA Director",
    dossierVersion: "4.0",
    createdAt: "15/05/2025, 10:00:00",
    updatedAt: "15/09/2025, 14:00:00",
  },
];
