import type { ControlledCopy } from './types';

export const MOCK_ALL_CONTROLLED_COPIES: ControlledCopy[] = [
  {
    id: "cc-001",
    documentNumber: "CC-2024-001",
    createdDate: "10/01/2024",
    createdTime: "09:30:45",
    openedBy: "John Smith",
    name: "Standard Operating Procedure for Material Receipt",
    status: "Ready for Distribution",
    validUntil: "10/01/2025",
    document: "SOP.0015.02",
    distributionList: "Warehouse Team, QC Team",
    version: "2.0",
    location: "Warehouse - Receiving",
    department: "Operations",
    reason: "Annual review and update",
  },
  {
    id: "cc-002",
    documentNumber: "CC-2024-002",
    createdDate: "08/01/2024",
    createdTime: "14:22:10",
    openedBy: "Sarah Johnson",
    name: "Work Instruction for Equipment Maintenance",
    status: "Distributed",
    validUntil: "31/12/2024",
    document: "WI.0028.01",
    distributionList: "Maintenance, Production",
    version: "1.0",
    recipientName: "Mike Maintenance",
    distributedDate: "09/01/2024",
    distributedBy: "Document Controller",
    department: "Maintenance",
  },
  {
    id: "cc-003",
    documentNumber: "CC-2024-003",
    createdDate: "05/01/2024",
    createdTime: "11:15:33",
    openedBy: "David Wilson",
    name: "Quality Control Inspection Procedure",
    status: "Obsolete",
    validUntil: "05/01/2024",
    document: "QCP.0112.03",
    distributionList: "QC Department",
    version: "3.0",
    department: "Quality Control",
    reason: "Superseded by new version",
  },
  {
    id: "cc-004",
    documentNumber: "CC-2024-004",
    createdDate: "03/01/2024",
    createdTime: "08:45:20",
    openedBy: "Emily Brown",
    name: "Training Manual for New Operators",
    status: "Closed - Cancelled",
    validUntil: "03/01/2024",
    document: "TM.0045.01",
    distributionList: "HR, Training Team",
    version: "1.0",
    department: "Human Resources",
    reason: "Cancelled due to policy change",
  },
  {
    id: "cc-005",
    documentNumber: "CC-2024-005",
    createdDate: "12/01/2024",
    createdTime: "16:50:12",
    openedBy: "Robert Lee",
    name: "Validation Protocol for Sterilization Process",
    status: "Ready for Distribution",
    validUntil: "30/06/2025",
    document: "VP.0087.02",
    distributionList: "Validation Team, Production",
    version: "2.0",
    location: "Sterilization Area",
    department: "Validation",
  },
  {
    id: "cc-006",
    documentNumber: "CC-2024-006",
    createdDate: "11/01/2024",
    createdTime: "10:20:55",
    openedBy: "Lisa Anderson",
    name: "Cleaning and Sanitization Procedure",
    status: "Distributed",
    validUntil: "15/12/2024",
    document: "SOP.0156.01",
    distributionList: "Cleaning Staff, QA",
    version: "1.0",
    recipientName: "Cleaning Supervisor",
    distributedDate: "11/01/2024",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-007",
    documentNumber: "CC-2023-089",
    createdDate: "20/12/2023",
    createdTime: "13:40:18",
    openedBy: "Michael Chen",
    name: "Batch Record Template - Legacy",
    status: "Obsolete",
    validUntil: "31/12/2023",
    document: "BRT.0234.05",
    distributionList: "Production, QC",
    version: "5.0",
    department: "Manufacturing",
    reason: "Replaced by new template",
  },
  {
    id: "cc-008",
    documentNumber: "CC-2024-008",
    createdDate: "09/01/2024",
    createdTime: "15:30:42",
    openedBy: "Anna Martinez",
    name: "Equipment Calibration Schedule",
    status: "Ready for Distribution",
    validUntil: "09/01/2025",
    document: "CS.0067.01",
    distributionList: "Calibration Lab, Maintenance",
    version: "1.0",
    location: "Calibration Lab",
    department: "Metrology",
  },
  {
    id: "cc-009",
    documentNumber: "CC-2024-009",
    createdDate: "07/01/2024",
    createdTime: "11:25:30",
    openedBy: "Peter Zhang",
    name: "Environmental Monitoring Procedure",
    status: "Distributed",
    validUntil: "07/01/2025",
    document: "SOP.0234.01",
    distributionList: "QA Team, Production",
    version: "1.0",
    recipientName: "QA Lead",
    distributedDate: "08/01/2024",
    distributedBy: "Quality Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-010",
    documentNumber: "CC-2023-101",
    createdDate: "15/11/2023",
    createdTime: "14:10:22",
    openedBy: "Jessica White",
    name: "Equipment Qualification Protocol - Old",
    status: "Closed - Cancelled",
    validUntil: "15/11/2023",
    document: "EQP.0156.02",
    distributionList: "Engineering, Validation",
    version: "2.0",
    department: "Engineering",
    reason: "Project cancelled",
  },
  {
    id: "cc-011",
    documentNumber: "CC-2024-011",
    createdDate: "01/02/2024",
    createdTime: "08:15:30",
    openedBy: "Thomas Anderson",
    name: "CAPA Investigation Procedure",
    status: "Ready for Distribution",
    validUntil: "01/02/2025",
    document: "SOP.0245.01",
    distributionList: "Quality Assurance, Production",
    version: "1.0",
    location: "QA Office",
    department: "Quality Assurance",
    reason: "New procedure implementation",
  },
  {
    id: "cc-012",
    documentNumber: "CC-2024-012",
    createdDate: "03/02/2024",
    createdTime: "13:45:12",
    openedBy: "Maria Garcia",
    name: "Deviation Management SOP",
    status: "Distributed",
    validUntil: "03/02/2025",
    document: "SOP.0189.02",
    distributionList: "All Departments",
    version: "2.0",
    recipientName: "Department Heads",
    distributedDate: "04/02/2024",
    distributedBy: "QA Director",
    department: "Quality Assurance",
  },
  {
    id: "cc-013",
    documentNumber: "CC-2024-013",
    createdDate: "05/02/2024",
    createdTime: "09:20:45",
    openedBy: "Robert Johnson",
    name: "Aseptic Processing Guidelines",
    status: "Ready for Distribution",
    validUntil: "05/08/2025",
    document: "SOP.0334.03",
    distributionList: "Manufacturing, QC",
    version: "3.0",
    location: "Aseptic Processing Area",
    department: "Manufacturing",
    reason: "Updated to comply with new regulations",
  },
  {
    id: "cc-014",
    documentNumber: "CC-2024-014",
    createdDate: "07/02/2024",
    createdTime: "14:30:22",
    openedBy: "Jennifer White",
    name: "Laboratory Safety Protocol",
    status: "Distributed",
    validUntil: "07/02/2025",
    document: "PROT.0056.01",
    distributionList: "Laboratory Staff",
    version: "1.0",
    recipientName: "Lab Safety Officer",
    distributedDate: "08/02/2024",
    distributedBy: "Safety Manager",
    department: "Safety & Compliance",
  },
  {
    id: "cc-015",
    documentNumber: "CC-2024-015",
    createdDate: "10/02/2024",
    createdTime: "11:10:55",
    openedBy: "Daniel Kim",
    name: "Supplier Audit Checklist",
    status: "Ready for Distribution",
    validUntil: "10/02/2025",
    document: "FORM.0123.02",
    distributionList: "Supply Chain, QA",
    version: "2.0",
    location: "Supply Chain Office",
    department: "Supply Chain",
    reason: "Enhanced audit requirements",
  },
  {
    id: "cc-016",
    documentNumber: "CC-2024-016",
    createdDate: "12/02/2024",
    createdTime: "10:05:18",
    openedBy: "Susan Miller",
    name: "Change Control Approval Form",
    status: "Distributed",
    validUntil: "12/12/2024",
    document: "FORM.0078.01",
    distributionList: "Change Control Board",
    version: "1.0",
    recipientName: "CCB Members",
    distributedDate: "13/02/2024",
    distributedBy: "Change Control Coordinator",
    department: "Quality Management",
  },
  {
    id: "cc-017",
    documentNumber: "CC-2023-145",
    createdDate: "20/10/2023",
    createdTime: "16:40:12",
    openedBy: "Kevin Brown",
    name: "Old Packaging Specification",
    status: "Obsolete",
    validUntil: "20/12/2023",
    document: "SPEC.0089.04",
    distributionList: "Packaging, QC",
    version: "4.0",
    department: "Packaging",
    reason: "New packaging material approved",
  },
  {
    id: "cc-018",
    documentNumber: "CC-2024-018",
    createdDate: "15/02/2024",
    createdTime: "09:55:30",
    openedBy: "Rachel Green",
    name: "Product Release Procedure",
    status: "Ready for Distribution",
    validUntil: "15/02/2025",
    document: "SOP.0412.01",
    distributionList: "QA Release, Warehouse",
    version: "1.0",
    location: "QA Release Department",
    department: "Quality Assurance",
    reason: "New GMP requirement",
  },
  {
    id: "cc-019",
    documentNumber: "CC-2024-019",
    createdDate: "16/02/2024",
    createdTime: "13:25:45",
    openedBy: "William Davis",
    name: "Complaint Investigation Work Instruction",
    status: "Distributed",
    validUntil: "16/02/2025",
    document: "WI.0145.02",
    distributionList: "Customer Service, QA",
    version: "2.0",
    recipientName: "Complaint Handler",
    distributedDate: "17/02/2024",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-020",
    documentNumber: "CC-2023-178",
    createdDate: "10/09/2023",
    createdTime: "11:30:20",
    openedBy: "Amanda Lopez",
    name: "Outdated Training Module - GMP Basics",
    status: "Closed - Cancelled",
    validUntil: "10/12/2023",
    document: "TM.0089.01",
    distributionList: "Training Department",
    version: "1.0",
    department: "Training",
    reason: "Replaced by e-learning platform",
  },
  {
    id: "cc-021",
    documentNumber: "CC-2026-021",
    createdDate: "20/01/2026",
    createdTime: "08:30:15",
    openedBy: "Christopher Lee",
    name: "Annual Product Quality Review Template",
    status: "Ready for Distribution",
    validUntil: "20/01/2027",
    document: "TEMP.0234.01",
    distributionList: "QA, Regulatory Affairs",
    version: "1.0",
    location: "QA Review Team",
    department: "Quality Assurance",
    reason: "Annual review cycle",
  },
  {
    id: "cc-022",
    documentNumber: "CC-2026-022",
    createdDate: "22/01/2026",
    createdTime: "10:15:40",
    openedBy: "Patricia Wilson",
    name: "Stability Testing Protocol",
    status: "Distributed",
    validUntil: "22/01/2027",
    document: "PROT.0167.03",
    distributionList: "Stability Lab, R&D",
    version: "3.0",
    recipientName: "Stability Manager",
    distributedDate: "23/01/2026",
    distributedBy: "Lab Director",
    department: "Quality Control",
  },
  {
    id: "cc-023",
    documentNumber: "CC-2026-023",
    createdDate: "25/01/2026",
    createdTime: "14:45:55",
    openedBy: "Charles Martinez",
    name: "Master Batch Record - Product A",
    status: "Ready for Distribution",
    validUntil: "25/01/2027",
    document: "MBR.0456.02",
    distributionList: "Production, Quality Control",
    version: "2.0",
    location: "Production Floor",
    department: "Manufacturing",
    reason: "Process optimization update",
  },
  {
    id: "cc-024",
    documentNumber: "CC-2026-024",
    createdDate: "28/01/2026",
    createdTime: "09:10:30",
    openedBy: "Michelle Taylor",
    name: "Document Control SOP",
    status: "Distributed",
    validUntil: "28/01/2027",
    document: "SOP.0001.05",
    distributionList: "All Departments",
    version: "5.0",
    recipientName: "All Staff",
    distributedDate: "29/01/2026",
    distributedBy: "Document Control Manager",
    department: "Quality Management",
  },
  {
    id: "cc-025",
    documentNumber: "CC-2026-025",
    createdDate: "01/02/2026",
    createdTime: "11:20:45",
    openedBy: "Steven Anderson",
    name: "Water System Maintenance Schedule",
    status: "Ready for Distribution",
    validUntil: "01/02/2027",
    document: "SCH.0089.01",
    distributionList: "Engineering, QA",
    version: "1.0",
    location: "Utilities Department",
    department: "Engineering",
    reason: "Preventive maintenance planning",
  },
  {
    id: "cc-026",
    documentNumber: "CC-2026-026",
    createdDate: "03/02/2026",
    createdTime: "15:35:20",
    openedBy: "Barbara Thompson",
    name: "Vendor Qualification Procedure",
    status: "Distributed",
    validUntil: "03/02/2027",
    document: "SOP.0278.02",
    distributionList: "Procurement, QA",
    version: "2.0",
    recipientName: "Procurement Manager",
    distributedDate: "04/02/2026",
    distributedBy: "QA Director",
    department: "Supply Chain",
  },
  {
    id: "cc-027",
    documentNumber: "CC-2025-234",
    createdDate: "15/08/2025",
    createdTime: "13:50:10",
    openedBy: "Richard Garcia",
    name: "Obsolete Equipment Cleaning Log",
    status: "Obsolete",
    validUntil: "15/12/2025",
    document: "LOG.0156.02",
    distributionList: "Production",
    version: "2.0",
    department: "Manufacturing",
    reason: "Equipment retired from service",
  },
  {
    id: "cc-028",
    documentNumber: "CC-2026-028",
    createdDate: "05/02/2026",
    createdTime: "08:40:35",
    openedBy: "Nancy Rodriguez",
    name: "Risk Assessment Template",
    status: "Ready for Distribution",
    validUntil: "05/02/2027",
    document: "TEMP.0345.01",
    distributionList: "Quality Management, Operations",
    version: "1.0",
    location: "Risk Management Office",
    department: "Quality Management",
    reason: "ISO compliance requirement",
  },
  {
    id: "cc-029",
    documentNumber: "CC-2026-029",
    createdDate: "07/02/2026",
    createdTime: "12:15:50",
    openedBy: "Joseph Hernandez",
    name: "Batch Sampling Procedure",
    status: "Distributed",
    validUntil: "07/02/2027",
    document: "SOP.0389.01",
    distributionList: "Production, QC Lab",
    version: "1.0",
    recipientName: "Lab Technicians",
    distributedDate: "08/02/2026",
    distributedBy: "QC Manager",
    department: "Quality Control",
  },
  {
    id: "cc-030",
    documentNumber: "CC-2024-130",
    createdDate: "20/06/2024",
    createdTime: "10:25:15",
    openedBy: "Linda Moore",
    name: "Cancelled Project Protocol - Phase II",
    status: "Closed - Cancelled",
    validUntil: "20/09/2024",
    document: "PROT.0234.01",
    distributionList: "R&D, Project Team",
    version: "1.0",
    department: "Research & Development",
    reason: "Project discontinued by management",
  },
  {
    id: "cc-031",
    documentNumber: "CC-2026-031",
    createdDate: "08/02/2026",
    createdTime: "14:55:30",
    openedBy: "Mark Jackson",
    name: "Out of Specification Investigation",
    status: "Ready for Distribution",
    validUntil: "08/02/2027",
    document: "SOP.0456.02",
    distributionList: "QC, QA, Production",
    version: "2.0",
    location: "Quality Department",
    department: "Quality Control",
    reason: "Enhanced investigation requirements",
  },
  {
    id: "cc-032",
    documentNumber: "CC-2026-032",
    createdDate: "09/02/2026",
    createdTime: "09:35:45",
    openedBy: "Karen White",
    name: "Internal Audit Checklist - Manufacturing",
    status: "Distributed",
    validUntil: "09/12/2026",
    document: "FORM.0234.01",
    distributionList: "Audit Team",
    version: "1.0",
    recipientName: "Lead Auditor",
    distributedDate: "10/02/2026",
    distributedBy: "QA Manager",
    department: "Quality Assurance",
  },
  {
    id: "cc-033",
    documentNumber: "CC-2026-033",
    createdDate: "10/02/2026",
    createdTime: "11:40:20",
    openedBy: "Brian Clark",
    name: "Analytical Method Validation Protocol",
    status: "Ready for Distribution",
    validUntil: "10/02/2027",
    document: "PROT.0289.01",
    distributionList: "QC Lab, Method Development",
    version: "1.0",
    location: "Analytical Laboratory",
    department: "Quality Control",
    reason: "New analytical method implementation",
  },
  {
    id: "cc-034",
    documentNumber: "CC-2026-034",
    createdDate: "11/02/2026",
    createdTime: "13:20:55",
    openedBy: "Elizabeth Lewis",
    name: "Data Integrity Procedure",
    status: "Distributed",
    validUntil: "11/02/2027",
    document: "SOP.0512.01",
    distributionList: "All Departments",
    version: "1.0",
    recipientName: "All Users",
    distributedDate: "11/02/2026",
    distributedBy: "IT & QA Director",
    department: "IT & Quality",
  },
  {
    id: "cc-035",
    documentNumber: "CC-2025-189",
    createdDate: "10/07/2025",
    createdTime: "15:10:40",
    openedBy: "George Hall",
    name: "Deprecated Equipment Manual - Model X200",
    status: "Obsolete",
    validUntil: "10/10/2025",
    document: "MAN.0167.01",
    distributionList: "Engineering",
    version: "1.0",
    department: "Engineering",
    reason: "Equipment model no longer in use",
  },
];

// --- Detail View Mock Data ---
export interface TimelineEvent {
  id: string;
  action: string;
  actor: string;
  timestamp: string;
  status: "completed" | "pending" | "rejected";
  comment?: string;
}

export const MOCK_CONTROLLED_COPY_DETAIL: ControlledCopy = {
  id: "1",
  documentNumber: "CC-2024-001",
  createdDate: "2024-01-05",
  createdTime: "09:30:45",
  openedBy: "John Smith",
  name: "Standard Operating Procedure for Quality Control Testing",
  status: "Ready for Distribution",
  validUntil: "2025-01-05",
  document: "SOP.0001.03",
  distributionList: "QA Lab, Production",
  version: "3.0",
  location: "Quality Assurance Lab",
  locationCode: "LOC-QA-01",
  department: "Quality Assurance",
  reason: "New production line setup",
  controlNumber: "CC-2024-001",
  documentId: "SOP.0001.03",
  documentTitle: "Standard Operating Procedure for Quality Control Testing",
  copyNumber: 1,
  totalCopies: 3,
  requestDate: "2024-01-05",
  requestedBy: "John Smith",
  currentStage: "Ready for Print",
  effectiveDate: "2024-01-05",
  distributedDate: undefined,
  distributedBy: undefined,
  recipientName: "QA Manager",
};

export const MOCK_TIMELINE: TimelineEvent[] = [
  {
    id: "1",
    action: "Request Submitted",
    actor: "John Smith",
    timestamp: "2024-01-05 09:30 AM",
    status: "completed",
    comment: "New production line setup",
  },
  {
    id: "2",
    action: "Approved by QM",
    actor: "Jane Doe (QA Manager)",
    timestamp: "2024-01-05 10:15 AM",
    status: "completed",
    comment: "Approved for printing",
  },
  {
    id: "3",
    action: "Printed & Issued",
    actor: "System",
    timestamp: "2024-01-05 11:00 AM",
    status: "completed",
    comment: "Controlled copy printed and delivered to location",
  },
  {
    id: "4",
    action: "Currently In Use",
    actor: "John Smith",
    timestamp: "2024-01-05 11:30 AM",
    status: "completed",
    comment: "Document received at Quality Assurance Lab",
  },
];

// --- Destroy View Mock Data ---
export const MOCK_DESTROY_CONTROLLED_COPY = {
  id: "cc-002",
  controlNumber: "CC-2024-002",
  copyNumber: 2,
  totalCopies: 5,
  documentId: "SOP-MFG-001",
  documentTitle: "Manufacturing Process Standard Operating Procedure",
  location: "Production Floor - Area B",
  recipientName: "John Manufacturing",
  distributedDate: "2024-01-15",
  status: "Distributed" as const,
};
