import type { EmployeeTrainingFile } from "../types";

// TODO: Replace with API call: GET /api/training/employees/training-files
export const MOCK_EMPLOYEE_TRAINING_FILES: EmployeeTrainingFile[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    employeeName: "John Smith",
    jobPosition: "QA Manager",
    department: "Quality Assurance",
    totalCoursesRequired: 5,
    coursesCompleted: 5,
    coursesInProgress: 0,
    coursesOverdue: 0,
    lastTrainingDate: "2026-01-15",
    averageScore: 92,
  },
  {
    id: "2",
    employeeId: "EMP-002",
    employeeName: "Sarah Johnson",
    jobPosition: "QC Analyst",
    department: "Quality Control",
    totalCoursesRequired: 6,
    coursesCompleted: 5,
    coursesInProgress: 1,
    coursesOverdue: 0,
    lastTrainingDate: "2026-01-20",
    averageScore: 88,
  },
  {
    id: "3",
    employeeId: "EMP-003",
    employeeName: "Michael Chen",
    jobPosition: "Production Operator",
    department: "Production",
    totalCoursesRequired: 4,
    coursesCompleted: 3,
    coursesInProgress: 0,
    coursesOverdue: 1,
    lastTrainingDate: "2026-01-10",
    averageScore: 78,
  },
  {
    id: "4",
    employeeId: "EMP-004",
    employeeName: "Emma Wilson",
    jobPosition: "Document Controller",
    department: "Documentation",
    totalCoursesRequired: 4,
    coursesCompleted: 4,
    coursesInProgress: 0,
    coursesOverdue: 0,
    lastTrainingDate: "2026-01-25",
    averageScore: 95,
  },
  {
    id: "5",
    employeeId: "EMP-005",
    employeeName: "David Brown",
    jobPosition: "Validation Engineer",
    department: "Engineering",
    totalCoursesRequired: 7,
    coursesCompleted: 5,
    coursesInProgress: 1,
    coursesOverdue: 1,
    lastTrainingDate: "2026-01-18",
    averageScore: 85,
  },
];
