import type { EmployeeTrainingFile, PendingSignatureRecord } from "../types";

// TODO: Replace with API call: GET /api/training/employees/training-files
export const MOCK_EMPLOYEE_TRAINING_FILES: EmployeeTrainingFile[] = [
  {
    id: "1",
    employeeId: "EMP-001",
    employeeName: "John Smith",
    jobPosition: "QA Manager",
    department: "Quality Assurance",
    businessUnit: "Pharma Manufacturing",
    email: "john.smith@eqms.com",
    totalCoursesRequired: 5,
    coursesCompleted: 5,
    coursesInProgress: 0,
    coursesOverdue: 0,
    coursesObsolete: 0,
    lastTrainingDate: "2026-01-15",
    nextDeadline: "2027-01-15",
    averageScore: 92,
    employeeType: "Internal",
    qualificationStatus: "Qualified",
    ojtRecords: [
      {
        id: "ojt-1",
        taskName: "Standard Operating Procedure for Internal Auditing",
        trainerName: "Dr. A. Smith",
        dateCompleted: "2026-01-14",
        status: "Completed",
        assessmentScore: 95,
        comments: "Candidate demonstrated deep understanding of audit checklists.",
        esignReason: "Confirmation of Practical Competence"
      },
      {
        id: "ojt-2",
        taskName: "Batch Release Verification Process",
        trainerName: "Dr. A. Smith",
        dateCompleted: "",
        status: "Pending",
      }
    ],
    completedCourses: [
      {
        id: "cc-1-1",
        courseCode: "SOP-QA-001",
        courseTitle: "Internal Audit Procedure",
        version: "v2.0",
        completionDate: "2026-04-05",
        expiryDate: "2027-04-05",
        score: 95,
        passingScore: 80,
        traineeName: "John Smith",
        traineeId: "EMP-001",
        traineeEsignDate: "2026-04-05T14:30:22Z",
        trainerName: "Dr. A. Smith",
        trainerId: "trainer-001",
        trainerEsignDate: "2026-05-13T09:15:00Z", // Simulation of signed later
        status: "Pass",
        pendingSignaturesCount: 0
      },
      {
        id: "cc-1-2",
        courseCode: "SOP-QA-007",
        courseTitle: "Deviation Management",
        version: "v1.0",
        completionDate: "2026-04-09",
        score: 85,
        passingScore: 80,
        traineeName: "John Smith",
        traineeId: "EMP-001",
        traineeEsignDate: "2026-04-09T10:00:00Z",
        trainerName: "Sarah Connor",
        trainerId: "trainer-002",
        trainerEsignDate: "",
        status: "Pass",
        pendingSignaturesCount: 1 // Ineligible due to trainer sign
      }
    ]
  },
  {
    id: "2",
    employeeId: "EMP-002",
    employeeName: "Sarah Johnson",
    jobPosition: "QC Analyst",
    department: "Quality Control",
    businessUnit: "Pharma Manufacturing",
    email: "sarah.johnson@eqms.com",
    totalCoursesRequired: 6,
    coursesCompleted: 4,
    coursesInProgress: 1,
    coursesOverdue: 0,
    coursesObsolete: 1, // Pending retraining due to v2.0 update
    lastTrainingDate: "2026-01-20",
    nextDeadline: "2026-04-30",
    averageScore: 88,
    employeeType: "Internal",
    qualificationStatus: "At Risk",
    completedCourses: [
      {
        id: "cc-2-1",
        courseCode: "SOP-QC-003",
        courseTitle: "HPLC Method Validation",
        version: "v1.0",
        completionDate: "2026-04-10",
        expiryDate: "2027-04-10",
        score: 88,
        passingScore: 80,
        traineeName: "Sarah Johnson",
        traineeId: "EMP-002",
        traineeEsignDate: "2026-04-10T11:20:00Z",
        trainerName: "Dr. A. Smith",
        trainerId: "trainer-001",
        trainerEsignDate: "2026-04-11T08:00:00Z",
        status: "Pass",
        pendingSignaturesCount: 0
      }
    ]
  },
  {
    id: "3",
    employeeId: "EMP-003",
    employeeName: "Michael Chen",
    jobPosition: "Production Operator",
    department: "Production",
    businessUnit: "Logistics & Supply",
    email: "michael.chen@eqms.com",
    totalCoursesRequired: 4,
    coursesCompleted: 3,
    coursesInProgress: 0,
    coursesOverdue: 1,
    coursesObsolete: 0,
    lastTrainingDate: "2026-01-10",
    nextDeadline: "2026-03-15",
    averageScore: 78,
    employeeType: "Contractor",
    qualificationStatus: "At Risk",
  },
  {
    id: "4",
    employeeId: "EMP-004",
    employeeName: "Emma Wilson",
    jobPosition: "Document Controller",
    department: "Documentation",
    businessUnit: "Corporate",
    email: "emma.wilson@eqms.com",
    totalCoursesRequired: 4,
    coursesCompleted: 4,
    coursesInProgress: 0,
    coursesOverdue: 0,
    coursesObsolete: 0,
    lastTrainingDate: "2026-01-25",
    nextDeadline: "2027-01-25",
    averageScore: 95,
    employeeType: "Internal",
    qualificationStatus: "Qualified",
  },
  {
    id: "5",
    employeeId: "EMP-005",
    employeeName: "David Brown",
    jobPosition: "Validation Engineer",
    department: "Engineering",
    businessUnit: "Pharma Manufacturing",
    email: "david.brown@eqms.com",
    totalCoursesRequired: 7,
    coursesCompleted: 0,
    coursesInProgress: 1,
    coursesOverdue: 0,
    coursesObsolete: 0,
    isNewHire: true, // For hero banner logic
    lastTrainingDate: "2026-03-01",
    nextDeadline: "2026-04-15",
    averageScore: 0,
    employeeType: "Internal",
    qualificationStatus: "In Training",
  },
];

// ─── Mock Pending Signatures (keyed by employee id) ──────────────────────────
export const MOCK_PENDING_SIGNATURES: Record<string, PendingSignatureRecord[]> = {
  "1": [
    {
      id: "ps-1-1",
      courseCode: "SOP-QA-001",
      courseTitle: "Internal Audit Procedure",
      version: "v2.0",
      missingRoles: ["Trainer"],
      completionDate: "2026-04-05",
      daysPending: 8,
      trainerId: "trainer-001",
      trainerName: "Dr. A. Smith",
      isObsolete: false,
    },
    {
      id: "ps-1-2",
      courseCode: "SOP-QA-007",
      courseTitle: "Deviation Management",
      version: "v1.0",
      missingRoles: ["Trainee", "Trainer"],
      completionDate: "2026-04-09",
      daysPending: 4,
      trainerId: "trainer-002",
      trainerName: "Sarah Connor",
      isObsolete: true,
    },
  ],
  "2": [
    {
      id: "ps-2-1",
      courseCode: "SOP-QC-003",
      courseTitle: "HPLC Method Validation",
      version: "v1.0",
      missingRoles: ["Trainee"],
      completionDate: "2026-04-10",
      daysPending: 3,
      trainerId: "trainer-001",
      trainerName: "Dr. A. Smith",
      isObsolete: true,
    },
  ],
  "3": [
    {
      id: "ps-3-1",
      courseCode: "SOP-PRD-002",
      courseTitle: "Cleanroom Gowning Procedure",
      version: "v3.0",
      missingRoles: ["Trainer"],
      completionDate: "2026-04-01",
      daysPending: 12,
      trainerId: "trainer-003",
      trainerName: "Michael Jordan",
      isObsolete: false,
    },
  ],
};
